In [1]:
# 우량주 분석
import datetime
today=  datetime.datetime.now()

first = '1995-05-02'
m6_ago = today - datetime.timedelta(days=183)
y1_ago = today - datetime.timedelta(days=365)
y2_ago = today - datetime.timedelta(days=2*365)
y3_ago  = today  - datetime.timedelta(days=3*365)
y4_ago  = today  - datetime.timedelta(days=4*365)
y5_ago = today - datetime.timedelta(days=5*365)
y6_ago = today - datetime.timedelta(days=6*365)

y8_ago = today - datetime.timedelta(days=8*365)
y10_ago = today - datetime.timedelta(days=10*365)

today = today.strftime('%Y-%m-%d')

m6_ago = m6_ago.strftime('%Y-%m-%d')
y1_ago = y1_ago.strftime('%Y-%m-%d')
y2_ago = y2_ago.strftime('%Y-%m-%d')
y3_ago = y3_ago.strftime('%Y-%m-%d')
y4_ago = y4_ago.strftime('%Y-%m-%d')
y5_ago = y5_ago.strftime('%Y-%m-%d')
y6_ago = y6_ago.strftime('%Y-%m-%d')

y8_ago = y8_ago.strftime('%Y-%m-%d')
y10_ago = y10_ago.strftime('%Y-%m-%d')
y1_ago

'2020-03-17'

In [2]:
# 기본 모듈 로드
import pandas as pd
from marcap import marcap_data
import matplotlib.pyplot as plt

In [3]:
# 그래프 설정
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

years = mdates.YearLocator()   # every year
months = mdates.MonthLocator()  # every month
years_fmt = mdates.DateFormatter('%Y')

plt.rcParams["figure.figsize"] = (16,4)
plt.rcParams['lines.linewidth'] = 0.5
plt.rcParams["axes.grid"] = True
plt.rcParams["axes.formatter.useoffset"] = False
plt.rcParams["xtick.minor.visible"] = True 

pd.options.display.float_format = '{:.2f}'.format

In [4]:
df = marcap_data(first, today)

c:\users\j\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py:3338: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):
c:\users\j\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py:3338: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

In [5]:
df['Dept'].unique()
df.reset_index(inplace=True)

In [6]:
df1 = df[df['Date']>y1_ago]
df2 = df[df['Date']>y2_ago]
df3 = df[df['Date']>y3_ago]
df4 = df[df['Date']>y4_ago]

df5 = df[df['Date']>y5_ago]
df6 = df[df['Date']>y6_ago]

df8 = df[df['Date']>y8_ago]
df10 = df[df['Date']>y10_ago]

df1_10 = df[df['Date']>y10_ago]
df1_10 = df1_10[df1_10['Date']<y1_ago]
df1_5 = df[df['Date']>y5_ago]
df1_5 = df1_5[df1_5['Date']<y1_ago]

In [7]:
dm6 = df[df['Date']>m6_ago]

In [8]:
d = df5

In [9]:
wuryang = d[d['Market'] == 'KOSPI']

In [10]:
codes = wuryang['Code'].unique()

In [11]:
len(codes)

990

In [12]:
data = list()
import scipy.stats
# for code in codes:


for code in codes:
    c = d[d['Code'] == code]
    if c['Date'].iloc[-1] == pd.to_datetime(today):
        latest_stocks = c['Stocks'].iloc[-1]
        c['Adj Close'] = c['Stocks'] * c['Close'] / latest_stocks

        c_min = c['Adj Close'].min()
        c_max = c['Adj Close'].max()
        c_mean = c['Adj Close'].mean()
        c_std = c['Adj Close'].std()

        c_current = c['Adj Close'].iloc[-1]

        c_norm = scipy.stats.norm(c_mean, c_std)

        data.append([code, c['Name'].iloc[-1], c_min, c_max, c_mean, c_std, c_current, c_mean/c_current, c_norm.cdf(c_current)])

<ipython-input-12-3ff44c464998>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c['Adj Close'] = c['Stocks'] * c['Close'] / latest_stocks

In [13]:
columns = ['Code', 'Name', 'Min', 'Max', 'Mean', 'Std', 'Current', 'M/C', 'Cdf']
wdf = pd.DataFrame(data)
wdf['C/M'] = 1 / wdf[7]
wdf['Max/Current'] = wdf[3]/wdf[6]
wdf.sort_values([8], ascending=[True]).to_csv('kospi-%s.csv' % today)
wdf.sort_values([8], ascending=[True]).head(60)

,0,1,2,3,4,5,6,7,8,C/M,Max/Current
77,000210,DL,61000.00,273824.77,190869.24,28080.33,78000.00,2.45,0.00,0.41,3.51
525,000215,DL우,37000.00,127559.51,78170.74,14089.06,39850.00,1.96,0.00,0.51,3.20
894,326030,SK바이오팜,104000.00,217000.00,163310.34,22121.93,111500.00,1.46,0.01,0.68,1.95
641,096300,베트남개발1,227.00,642.54,393.98,81.86,229.00,1.72,0.02,0.58,2.81
574,004450,삼화왕관,32100.00,55100.00,45532.59,4223.48,37750.00,1.21,0.03,0.83,1.46
736,153360,하이골드3호,1170.00,2890.00,1695.55,246.94,1245.00,1.36,0.03,0.73,2.32
540,019685,대교우B,2175.00,5690.00,4375.24,994.39,2595.00,1.69,0.04,0.59,2.19
356,000155,두산우,25800.00,92604.19,69672.91,17988.37,38600.00,1.80,0.04,0.55,2.40
36,021240,코웨이,48250.00,118091.42,87695.80,12160.57,66800.00,1.31,0.04,0.76,1.77
391,168490,한국패러랠,1890.00,2665.00,2344.54,237.24,1955.00,1.20,0.05,0.83,1.36
68,012750,에스원,73800.00,115000.00,94058.56,6869.98,82900.00,1.13,0.05,0.88,1.39
225,003920,남양유업,255000.00,944000.00,578928.63,174057.96,297500.00,1.95,0.05,0.51,3.17
17,033780,KT&G,63600.00,137000.00,101068.68,13022.01,80100.00,1.26,0.05,0.79,1.71
498,034590,인천도시가스,20950.00,32050.00,28932.34,2266.60,25350.00,1.14,0.06,0.88,1.26
20,000810,삼성화재,126000.00,309000.00,251919.66,40622.39,188000.00,1.34,0.06,0.75,1.64
182,019680,대교,3075.00,11000.00,6827.47,1720.75,4135.00,1.65,0.06,0.61,2.66
115,000150,두산,26050.00,177326.56,107927.24,38979.88,48800.00,2.21,0.06,0.45,3.63
409,007980,태평양물산,1129.89,4659.29,2947.50,677.65,1940.00,1.52,0.07,0.66,2.40
381,015360,예스코홀딩스,26300.00,44700.00,38097.68,2810.29,33950.00,1.12,0.07,0.89,1.32
663,000157,두산2우B,25800.00,108500.00,75376.77,12379.19,57200.00,1.32,0.07,0.76,1.90
470,152550,한국ANKOR유전,1560.00,2110.00,1829.33,115.89,1660.00,1.10,0.07,0.91,1.27
215,002960,한국쉘석유,206000.00,501000.00,349609.30,69745.06,248000.00,1.41,0.07,0.71,2.02
352,004970,신라교역,6850.00,17800.00,13477.81,2372.69,10050.00,1.34,0.07,0.75,1.77
390,025560,미래산업,2494.02,14331.46,7069.20,2603.27,3315.00,2.13,0.07,0.47,4.32
499,000850,화천기공,23950.00,62900.00,45280.18,9268.31,31950.00,1.42,0.08,0.71,1.97
575,084670,동양고속,20856.51,36502.02,28951.05,3504.78,23950.00,1.21,0.08,0.83,1.52
186,071320,지역난방공사,26000.00,87400.00,58776.96,14639.43,38150.00,1.54,0.08,0.65,2.29
274,017940,E1,22400.00,74000.00,55226.71,9673.63,41700.00,1.32,0.08,0.76,1.77
725,155900,바다로19호,1885.00,3600.00,2752.11,232.66,2430.00,1.13,0.08,0.88,1.48
734,172580,하이골드12호,1920.00,3265.00,2455.70,289.90,2055.00,1.19,0.08,0.84,1.59
48,005830,DB손해보험,23800.00,83800.00,60614.15,11684.80,44500.00,1.36,0.08,0.73,1.88
305,001130,대한제분,91500.00,240500.00,172255.30,20160.27,144500.00,1.19,0.08,0.84,1.66
377,007660,이수페타시스,1785.00,7070.00,4510.59,812.59,3420.00,1.32,0.09,0.76,2.07
277,078520,에이블씨엔씨,5790.00,21617.33,12320.38,3390.16,7870.00,1.57,0.09,0.64,2.75
750,005725,넥센우,2025.00,6120.00,4111.20,891.42,2960.00,1.39,0.10,0.72,2.07
219,000815,삼성화재우,86100.00,206500.00,171162.15,21916.03,143000.00,1.20,0.10,0.84,1.44
461,035000,지투알,3400.00,11600.00,7766.81,1683.47,5610.00,1.38,0.10,0.72,2.07
480,005800,신영와코루,64300.00,189000.00,130849.55,28222.75,94700.00,1.38,0.10,0.72,2.00
396,091090,세원셀론텍,1282.00,5816.32,2814.20,672.41,1955.00,1.44,0.10,0.69,2.98
176,009970,영원무역홀딩스,27400.00,72000.00,52891.97,9377.31,40950.00,1.29,0.10,0.77,1.76
268,008060,대덕,4833.88,29117.26,14497.28,6053.00,6820.00,2.13,0.10,0.47,4.27
329,013520,화승코퍼레이션,1483.39,5888.40,3277.50,962.33,2060.00,1.59,0.10,0.63,2.86
273,005720,넥센,2985.00,8694.79,6376.72,1378.88,4640.00,1.37,0.10,0.73,1.87
477,000650,천일고속,40950.00,128000.00,80909.71,13115.14,64600.00,1.25,0.11,0.80,1.98
180,037560,LG헬로비전,2420.00,13900.00,7654.75,2406.04,4685.00,1.63,0.11,0.61,2.97
580,001210,금호전기,1285.28,7850.08,4334.68,1407.73,2600.00,1.67,0.11,0.60,3.02
295,004150,한솔홀딩스,2414.86,9075.36,5501.04,1529.13,3625.00,1.52,0.11,0.66,2.50
793,000325,노루홀딩스우,10000.00,22700.00,17960.09,1805.06,15750.00,1.14,0.11,0.88,1.44
188,053210,스카이라이프,4760.00,18500.00,12455.31,3287.07,8440.00,1.48,0.11,0.68,2.19
241,029530,신도리코,19500.00,73100.00,45894.70,12947.88,30100.00,1.52,0.11,0.66,2.43
57,002380,KCC,107000.00,525659.40,349813.61,120415.21,204000.00,1.71,0.11,0.58,2.58
600,006570,대림통상,2400.00,7580.00,4850.91,841.54,3840.00,1.26,0.11,0.79,1.97
496,014990,인디에프,926.00,4300.00,2081.04,633.07,1330.00,1.56,0.12,0.64,3.23
901,36328K,티와이홀딩스우,21100.00,45500.00,26426.50,3861.94,21900.00,1.21,0.12,0.83,2.08
296,005500,삼진제약,16650.00,58200.00,33371.74,7399.49,24700.00,1.35,0.12,0.74,2.36
50,078930,GS,30300.00,76700.00,51666.56,9891.20,40100.00,1.29,0.12,0.78,1.91
75,001450,현대해상,17700.00,49200.00,32895.15,7679.46,23950.00,1.37,0.12,0.73,2.05
285,214420,토니모리,6300.00,37666.67,16048.28,6774.29,8200.00,1.96,0.12,0.51,4.59
720,008500,일정실업,8560.00,32350.00,21618.00,6190.28,14450.00,1.50,0.12,0.67,2.24
145,002270,롯데푸드,211500.00,1128825.56,623552.49,216137.07,373500.00,1.67,0.12,0.60,3.02

In [14]:
df[df['Code'] == '003380'].iloc[-1]['Close']

8930.0

In [15]:
df[df['Code'] == '054800'].iloc[-1]['Close']

12650.0

In [16]:
df[df['Code'] == '054950'].iloc[-1]

Date            2021-03-17 00:00:00
Code                         054950
Name                          제이브이엠
Market                       KOSDAQ
Dept                          우량기업부
Close                       36500.0
ChangeCode                        1
Changes                       300.0
ChagesRatio                     NaN
Open                        36550.0
High                        36650.0
Low                         36000.0
Volume                      30184.0
Amount                 1097527900.0
Marcap               231078142000.0
Stocks                    6330908.0
MarketId                        KSQ
Rank                            873
ChangesRatio                   0.83
Name: 11195385, dtype: object