In [1]:
import pandas as pd
df = pd.read_csv('data/marcap-2020.csv.gz', dtype={"Code": str}, parse_dates=['Date'])

In [2]:
df.head(10)

,Code,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId,Rank,Date
0,005930,삼성전자,KOSPI,NaN,55200.0,2,-600.0,-1.08,55500.0,56000.0,55000.0,12993228.0,7.196632e+11,3.295320e+14,5969782550,STK,1,2020-01-02
1,000660,SK하이닉스,KOSPI,NaN,94700.0,1,600.0,0.64,96000.0,96200.0,94100.0,2342070.0,2.228414e+11,6.894182e+13,728002365,STK,2,2020-01-02
2,005935,삼성전자우,KOSPI,NaN,45600.0,1,200.0,0.44,45750.0,45950.0,45150.0,1512362.0,6.894333e+10,3.752363e+13,822886700,STK,3,2020-01-02
3,035420,NAVER,KOSPI,NaN,182500.0,2,-4000.0,-2.14,187500.0,188000.0,182000.0,300640.0,5.530956e+10,3.007844e+13,164813395,STK,4,2020-01-02
4,207940,삼성바이오로직스,KOSPI,NaN,428500.0,2,-4500.0,-1.04,433000.0,439500.0,425500.0,108281.0,4.647975e+10,2.835170e+13,66165000,STK,5,2020-01-02
5,005380,현대차,KOSPI,NaN,118000.0,2,-2500.0,-2.07,121000.0,121000.0,118000.0,556532.0,6.620498e+10,2.521285e+13,213668187,STK,6,2020-01-02
6,012330,현대모비스,KOSPI,NaN,247500.0,2,-8500.0,-3.32,254500.0,256000.0,247500.0,214585.0,5.362298e+10,2.358841e+13,95306694,STK,7,2020-01-02
7,068270,셀트리온,KOSPI,NaN,180000.0,2,-1000.0,-0.55,181000.0,183000.0,176000.0,621826.0,1.113250e+11,2.310081e+13,128337853,STK,8,2020-01-02
8,051910,LG화학,KOSPI,NaN,314000.0,2,-3500.0,-1.10,321000.0,321000.0,313500.0,139496.0,4.418112e+10,2.216600e+13,70592343,STK,9,2020-01-02
9,005490,POSCO,KOSPI,NaN,236000.0,2,-500.0,-0.21,236000.0,240000.0,234500.0,213578.0,5.061737e+10,2.057609e+13,87186835,STK,10,2020-01-02

In [3]:
df = pd.read_csv("data/marcap-2021.csv.gz")

In [4]:
df.head(10)

,Code,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId,Rank,Date
0,005930,삼성전자,KOSPI,NaN,83000.0,1,2000.0,2.47,81000.0,84400.0,80200.0,38655276.0,3.185357e+12,4.954920e+14,5969782550,STK,1,2021-01-04
1,000660,SK하이닉스,KOSPI,NaN,126000.0,1,7500.0,6.33,124500.0,128000.0,120500.0,7995016.0,9.942765e+11,9.172830e+13,728002365,STK,2,2021-01-04
2,051910,LG화학,KOSPI,NaN,889000.0,1,65000.0,7.89,849000.0,900000.0,835000.0,858451.0,7.479297e+11,6.275659e+13,70592343,STK,3,2021-01-04
3,005935,삼성전자우,KOSPI,NaN,74400.0,1,800.0,1.09,73700.0,75300.0,73600.0,5455139.0,4.056852e+11,6.122277e+13,822886700,STK,4,2021-01-04
4,207940,삼성바이오로직스,KOSPI,NaN,829000.0,1,3000.0,0.36,819000.0,838000.0,804000.0,182864.0,1.498895e+11,5.485078e+13,66165000,STK,5,2021-01-04
5,035420,NAVER,KOSPI,NaN,293000.0,1,500.0,0.17,291500.0,294000.0,285500.0,947178.0,2.746358e+11,4.812917e+13,164263395,STK,6,2021-01-04
6,068270,셀트리온,KOSPI,NaN,347500.0,2,-11500.0,-3.20,351500.0,354500.0,343000.0,2006483.0,6.982387e+11,4.691174e+13,134997805,STK,7,2021-01-04
7,006400,삼성SDI,KOSPI,NaN,671000.0,1,43000.0,6.85,660000.0,682000.0,640000.0,694737.0,4.605973e+11,4.614100e+13,68764530,STK,8,2021-01-04
8,005380,현대차,KOSPI,NaN,207500.0,1,15500.0,8.07,194000.0,211000.0,193500.0,5651695.0,1.162238e+12,4.433615e+13,213668187,STK,9,2021-01-04
9,035720,카카오,KOSPI,NaN,396000.0,1,6500.0,1.67,392000.0,396500.0,385500.0,853740.0,3.353581e+11,3.502088e+13,88436556,STK,10,2021-01-04

In [5]:
df

,Code,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId,Rank,Date
0,005930,삼성전자,KOSPI,NaN,83000.0,1,2000.0,2.47,81000.0,84400.0,80200.0,38655276.0,3.185357e+12,4.954920e+14,5969782550,STK,1,2021-01-04
1,000660,SK하이닉스,KOSPI,NaN,126000.0,1,7500.0,6.33,124500.0,128000.0,120500.0,7995016.0,9.942765e+11,9.172830e+13,728002365,STK,2,2021-01-04
2,051910,LG화학,KOSPI,NaN,889000.0,1,65000.0,7.89,849000.0,900000.0,835000.0,858451.0,7.479297e+11,6.275659e+13,70592343,STK,3,2021-01-04
3,005935,삼성전자우,KOSPI,NaN,74400.0,1,800.0,1.09,73700.0,75300.0,73600.0,5455139.0,4.056852e+11,6.122277e+13,822886700,STK,4,2021-01-04
4,207940,삼성바이오로직스,KOSPI,NaN,829000.0,1,3000.0,0.36,819000.0,838000.0,804000.0,182864.0,1.498895e+11,5.485078e+13,66165000,STK,5,2021-01-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33878,238500,로보쓰리,KONEX,일반기업부,585.0,2,-8.0,-1.35,610.0,610.0,550.0,3299.0,1.912680e+06,2.739067e+09,4682166,KNX,2524,2021-01-21
33879,001529,동양3우B,KOSPI,NaN,29500.0,2,-400.0,-1.34,29550.0,29550.0,29500.0,377.0,1.112450e+07,2.646799e+09,89722,STK,2525,2021-01-21
33880,224020,에스케이씨에스,KONEX,일반기업부,799.0,1,99.0,14.14,800.0,800.0,799.0,546.0,4.363550e+05,2.456925e+09,3075000,KNX,2527,2021-01-21
33881,242350,피엔아이컴퍼니,KONEX,일반기업부,459.0,1,2.0,0.44,461.0,510.0,458.0,2209.0,1.024696e+06,2.185538e+09,4761520,KNX,2529,2021-01-21
33882,225860,엠앤씨생명과학,KONEX,일반기업부,85.0,2,-1.0,-1.16,77.0,98.0,77.0,124108.0,1.160590e+07,9.654378e+08,11358092,KNX,2532,2021-01-21

In [6]:
df.iloc[0]

Code                      005930
Name                        삼성전자
Market                     KOSPI
Dept                         NaN
Close                    83000.0
ChangeCode                     1
Changes                   2000.0
ChagesRatio                 2.47
Open                     81000.0
High                     84400.0
Low                      80200.0
Volume                38655276.0
Amount           3185356823460.0
Marcap         495491951650000.0
Stocks                5969782550
MarketId                     STK
Rank                           1
Date                  2021-01-04
Name: 0, dtype: object

In [7]:
df.iloc[0]["Code"]

'005930'

In [8]:
df.iloc[0]["Date"]

'2021-01-04'

In [9]:
df["Code"].dtype

dtype('O')

In [10]:
df["Date"].dtype

dtype('O')

In [11]:
df

,Code,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId,Rank,Date
0,005930,삼성전자,KOSPI,NaN,83000.0,1,2000.0,2.47,81000.0,84400.0,80200.0,38655276.0,3.185357e+12,4.954920e+14,5969782550,STK,1,2021-01-04
1,000660,SK하이닉스,KOSPI,NaN,126000.0,1,7500.0,6.33,124500.0,128000.0,120500.0,7995016.0,9.942765e+11,9.172830e+13,728002365,STK,2,2021-01-04
2,051910,LG화학,KOSPI,NaN,889000.0,1,65000.0,7.89,849000.0,900000.0,835000.0,858451.0,7.479297e+11,6.275659e+13,70592343,STK,3,2021-01-04
3,005935,삼성전자우,KOSPI,NaN,74400.0,1,800.0,1.09,73700.0,75300.0,73600.0,5455139.0,4.056852e+11,6.122277e+13,822886700,STK,4,2021-01-04
4,207940,삼성바이오로직스,KOSPI,NaN,829000.0,1,3000.0,0.36,819000.0,838000.0,804000.0,182864.0,1.498895e+11,5.485078e+13,66165000,STK,5,2021-01-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33878,238500,로보쓰리,KONEX,일반기업부,585.0,2,-8.0,-1.35,610.0,610.0,550.0,3299.0,1.912680e+06,2.739067e+09,4682166,KNX,2524,2021-01-21
33879,001529,동양3우B,KOSPI,NaN,29500.0,2,-400.0,-1.34,29550.0,29550.0,29500.0,377.0,1.112450e+07,2.646799e+09,89722,STK,2525,2021-01-21
33880,224020,에스케이씨에스,KONEX,일반기업부,799.0,1,99.0,14.14,800.0,800.0,799.0,546.0,4.363550e+05,2.456925e+09,3075000,KNX,2527,2021-01-21
33881,242350,피엔아이컴퍼니,KONEX,일반기업부,459.0,1,2.0,0.44,461.0,510.0,458.0,2209.0,1.024696e+06,2.185538e+09,4761520,KNX,2529,2021-01-21
33882,225860,엠앤씨생명과학,KONEX,일반기업부,85.0,2,-1.0,-1.16,77.0,98.0,77.0,124108.0,1.160590e+07,9.654378e+08,11358092,KNX,2532,2021-01-21

In [12]:
df.dtypes

Code            object
Name            object
Market          object
Dept            object
Close          float64
ChangeCode       int64
Changes        float64
ChagesRatio    float64
Open           float64
High           float64
Low            float64
Volume         float64
Amount         float64
Marcap         float64
Stocks           int64
MarketId        object
Rank             int64
Date            object
dtype: object

In [13]:
df = pd.read_csv("data/marcap-2021.csv.gz", dtype={"Code": str}, parse_dates=["Date"])

In [14]:
df.dtypes

Code                   object
Name                   object
Market                 object
Dept                   object
Close                 float64
ChangeCode              int64
Changes               float64
ChagesRatio           float64
Open                  float64
High                  float64
Low                   float64
Volume                float64
Amount                float64
Marcap                float64
Stocks                  int64
MarketId               object
Rank                    int64
Date           datetime64[ns]
dtype: object

In [15]:
df["Code"].dtype

dtype('O')

In [16]:
df["Date"].dtype

dtype('<M8[ns]')

In [17]:
df[2000:2010]

,Code,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId,Rank,Date
2000,039310,세중,KOSDAQ,중견기업부,2835.0,1,80.0,2.90,2765.0,2840.0,2725.0,166256.0,4.644917e+08,5.137493e+10,18121667,KSQ,2040,2021-01-04
2001,067920,이글루시큐리티,KOSDAQ,벤처기업부,4670.0,2,-100.0,-2.10,4875.0,4875.0,4670.0,81495.0,3.824009e+08,5.135188e+10,10996119,KSQ,2041,2021-01-04
2002,010770,평화홀딩스,KOSPI,NaN,3510.0,2,-20.0,-0.57,3545.0,3610.0,3510.0,103832.0,3.691018e+08,5.133539e+10,14625466,STK,2042,2021-01-04
2003,003680,한성기업,KOSPI,NaN,8250.0,2,-60.0,-0.72,8310.0,8370.0,8060.0,57044.0,4.648186e+08,5.122850e+10,6209515,STK,2043,2021-01-04
2004,046070,코다코,KOSDAQ,투자주의환기종목(소속부없음),1310.0,1,20.0,1.55,1290.0,1380.0,1250.0,1631992.0,2.135883e+09,5.117418e+10,39064256,KSQ,2044,2021-01-04
2005,046310,백금T&A,KOSDAQ,중견기업부,3115.0,1,85.0,2.81,3040.0,3115.0,3025.0,1404315.0,4.382419e+09,5.114407e+10,16418641,KSQ,2045,2021-01-04
2006,009140,경인전자,KOSPI,NaN,32550.0,4,7500.0,29.94,32000.0,32550.0,30500.0,52804.0,1.709446e+09,5.112944e+10,1570797,STK,2046,2021-01-04
2007,317830,에스피시스템스,KOSDAQ,벤처기업부,6250.0,1,50.0,0.81,6150.0,6310.0,6150.0,44184.0,2.764136e+08,5.091062e+10,8145700,KSQ,2047,2021-01-04
2008,007120,미래아이앤지,KOSPI,NaN,393.0,2,-1.0,-0.25,385.0,402.0,385.0,2082435.0,8.201737e+08,5.088727e+10,129484148,STK,2048,2021-01-04
2009,213090,미래테크놀로지,KOSDAQ,중견기업부,8310.0,1,80.0,0.97,8240.0,8340.0,8180.0,22091.0,1.822278e+08,5.086375e+10,6120788,KSQ,2049,2021-01-04

In [18]:
df[df["Changes"] == 0.0]

,Code,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId,Rank,Date
75,139480,이마트,KOSPI,NaN,151500.0,3,0.0,0.0,152000.0,153000.0,151500.0,210270.0,3.201744e+10,4.223187e+12,27875819,STK,76,2021-01-04
77,088980,맥쿼리인프라,KOSPI,NaN,10650.0,3,0.0,0.0,10650.0,10700.0,10550.0,1756502.0,1.862169e+10,3.963850e+12,372192485,STK,78,2021-01-04
87,293490,카카오게임즈,KOSDAQ,중견기업부,46000.0,3,0.0,0.0,46300.0,46300.0,45750.0,511567.0,2.349348e+10,3.406375e+12,74051634,KSQ,88,2021-01-04
113,001040,CJ,KOSPI,NaN,92100.0,3,0.0,0.0,92600.0,92600.0,90500.0,173838.0,1.597755e+10,2.687202e+12,29176998,STK,115,2021-01-04
160,047050,포스코인터내셔널,KOSPI,NaN,14550.0,3,0.0,0.0,14600.0,14650.0,14300.0,664410.0,9.633418e+09,1.795108e+12,123375149,STK,162,2021-01-04
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33832,323280,신영스팩5호,KOSDAQ,SPAC(소속부없음),2115.0,3,0.0,0.0,2115.0,2115.0,2115.0,2.0,4.230000e+03,7.413075e+09,3505000,KSQ,2471,2021-01-21
33846,347140,케이프이에스제4호,KOSDAQ,SPAC(소속부없음),2060.0,3,0.0,0.0,2055.0,2060.0,2055.0,601.0,1.237560e+06,6.198540e+09,3009000,KSQ,2488,2021-01-21
33849,308700,테크엔,KONEX,일반기업부,1500.0,3,0.0,0.0,1500.0,1500.0,1500.0,385.0,5.775000e+05,6.000000e+09,4000000,KNX,2492,2021-01-21
33862,014915,성문전자우,KOSPI,NaN,8200.0,3,0.0,0.0,8210.0,8210.0,8120.0,8729.0,7.118429e+07,4.920000e+09,600000,STK,2506,2021-01-21
33870,001527,동양2우B,KOSPI,NaN,11650.0,3,0.0,0.0,11700.0,11700.0,11600.0,343.0,3.999300e+06,3.594829e+09,308569,STK,2515,2021-01-21