In [1]:
# 우량주 분석
import datetime
today=  datetime.datetime.now()

first = '1995-05-02'

y1_ago = today - datetime.timedelta(days=365)
y2_ago = today - datetime.timedelta(days=2*365)
y3_ago  = today  - datetime.timedelta(days=3*365)
y4_ago  = today  - datetime.timedelta(days=4*365)
y5_ago = today - datetime.timedelta(days=5*365)
y6_ago = today - datetime.timedelta(days=6*365)
y8_ago = today - datetime.timedelta(days=8*365)
y10_ago = today - datetime.timedelta(days=10*365)

today = today.strftime('%Y-%m-%d')

y1_ago = y1_ago.strftime('%Y-%m-%d')
y2_ago = y2_ago.strftime('%Y-%m-%d')
y3_ago = y3_ago.strftime('%Y-%m-%d')
y4_ago = y4_ago.strftime('%Y-%m-%d')
y5_ago = y5_ago.strftime('%Y-%m-%d')
y6_ago = y6_ago.strftime('%Y-%m-%d')
y8_ago = y8_ago.strftime('%Y-%m-%d')
y10_ago = y10_ago.strftime('%Y-%m-%d')
y1_ago

'2020-03-16'

In [2]:
# 기본 모듈 로드
import pandas as pd
from marcap import marcap_data
import matplotlib.pyplot as plt

In [3]:
# 그래프 설정
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

years = mdates.YearLocator()   # every year
months = mdates.MonthLocator()  # every month
years_fmt = mdates.DateFormatter('%Y')

plt.rcParams["figure.figsize"] = (16,4)
plt.rcParams['lines.linewidth'] = 0.5
plt.rcParams["axes.grid"] = True
plt.rcParams["axes.formatter.useoffset"] = False
plt.rcParams["xtick.minor.visible"] = True 

pd.options.display.float_format = '{:.2f}'.format

In [4]:
df = marcap_data(first, today)

c:\users\j\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py:3338: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):
c:\users\j\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py:3338: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

In [5]:
df['Dept'].unique()
df.reset_index(inplace=True)

In [6]:
df1 = df[df['Date']>y1_ago]
df2 = df[df['Date']>y2_ago]
df3 = df[df['Date']>y3_ago]
df4 = df[df['Date']>y4_ago]

df5 = df[df['Date']>y5_ago]
df6 = df[df['Date']>y6_ago]

df8 = df[df['Date']>y8_ago]
df10 = df[df['Date']>y10_ago]

df1_10 = df[df['Date']>y10_ago]
df1_10 = df1_10[df1_10['Date']<y1_ago]
df1_5 = df[df['Date']>y5_ago]
df1_5 = df1_5[df1_5['Date']<y1_ago]

In [7]:
d = df4

In [8]:
wuryang = d[d['Dept'] == '중견기업부']

In [9]:
codes = wuryang['Code'].unique()

In [10]:
len(codes)

867

In [11]:
data = list()
import scipy.stats
# for code in codes:


for code in codes:
    c = d[d['Code'] == code]
    if c['Date'].iloc[-1] == pd.to_datetime(today):
        latest_stocks = c['Stocks'].iloc[-1]
        c['Adj Close'] = c['Stocks'] * c['Close'] / latest_stocks

        c_min = c['Adj Close'].min()
        c_max = c['Adj Close'].max()
        c_mean = c['Adj Close'].mean()
        c_std = c['Adj Close'].std()

        c_current = c['Adj Close'].iloc[-1]

        c_norm = scipy.stats.norm(c_mean, c_std)

        data.append([code, c['Name'].iloc[-1], c_min, c_max, c_mean, c_std, c_current, c_mean/c_current, c_norm.cdf(c_current)])

<ipython-input-11-3ff44c464998>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c['Adj Close'] = c['Stocks'] * c['Close'] / latest_stocks

In [12]:
columns = ['Code', 'Name', 'Min', 'Max', 'Mean', 'Std', 'Current', 'M/C' 'Cdf']
wdf = pd.DataFrame(data)
wdf['C/M'] = 1 / wdf[7]
wdf.sort_values([8], ascending=[True]).head(60)

,0,1,2,3,4,5,6,7,8,C/M
664,038340,UCI,678.23,4251.70,2726.72,813.91,806.00,3.38,0.01,0.30
104,138690,엘아이에스,4525.00,15438.67,10587.91,2335.00,5360.00,1.98,0.01,0.51
690,101400,엔시트론,628.86,3494.95,1770.58,532.30,801.00,2.21,0.03,0.45
176,044180,KD,811.00,5958.70,2792.12,950.43,1165.00,2.40,0.04,0.42
293,017250,인터엠,1350.00,4295.00,2538.59,611.52,1510.00,1.68,0.05,0.59
752,332570,와이팜,10050.00,18800.00,13882.57,1732.14,11000.00,1.26,0.05,0.79
691,062970,피피아이,3800.00,13400.00,8248.93,1829.15,5470.00,1.51,0.06,0.66
63,060560,홈센타홀딩스,896.00,3085.35,1521.82,375.89,955.00,1.59,0.07,0.63
401,060380,동양에스텍,1720.00,5410.00,3136.45,422.64,2510.00,1.25,0.07,0.80
90,008290,원풍물산,1610.00,6387.04,3295.51,712.01,2260.00,1.46,0.07,0.69
750,330350,위더스제약,17700.00,34400.00,21793.31,2347.23,18400.00,1.18,0.07,0.84
559,026040,제이에스티나,1390.00,11150.00,5380.77,2314.06,2055.00,2.62,0.08,0.38
567,053110,소리바다,214.00,1669.55,690.58,292.47,272.00,2.54,0.08,0.39
141,204630,스튜디오산타클로스,1845.79,5837.62,3224.86,831.35,2040.00,1.58,0.08,0.63
742,223250,드림씨아이에스,14800.00,31424.65,20814.60,3275.87,16150.00,1.29,0.08,0.78
464,099440,스맥,1082.51,3853.91,2628.85,620.23,1750.00,1.50,0.08,0.67
160,043710,서울리거,536.86,3573.42,1823.11,639.45,918.00,1.99,0.08,0.50
771,356860,티엘비,41550.00,67600.00,50663.11,5753.20,42700.00,1.19,0.08,0.84
496,225190,삼양옵틱스,7497.99,19717.22,13534.07,3102.06,9250.00,1.46,0.08,0.68
40,052790,액토즈소프트,3930.00,23650.00,13325.20,3504.07,8570.00,1.55,0.09,0.64
565,173940,에프엔씨엔터,3615.00,13900.00,7542.75,1381.12,5720.00,1.32,0.09,0.76
710,037950,엘컴텍,1225.00,3015.00,1954.40,355.58,1490.00,1.31,0.10,0.76
685,076610,해성옵틱스,792.15,3706.16,1975.23,603.14,1220.00,1.62,0.11,0.62
407,099410,동방선기,965.00,4850.00,2422.94,645.80,1615.00,1.50,0.11,0.67
547,014620,성광벤드,4095.00,14150.00,9803.81,1963.30,7360.00,1.33,0.11,0.75
53,065060,지엔코,895.00,3630.00,1694.71,579.87,989.00,1.71,0.11,0.58
286,033340,좋은사람들,926.14,4572.48,2019.36,770.27,1085.00,1.86,0.11,0.54
549,137940,넥스트아이,550.00,3791.84,2189.04,763.48,1270.00,1.72,0.11,0.58
726,043090,큐브앤컴퍼니,1258.12,6147.69,3073.69,1053.95,1815.00,1.69,0.12,0.59
444,016100,리더스코스메틱,2128.07,24407.73,10627.79,5984.35,3485.00,3.05,0.12,0.33
634,102940,코오롱생명과학,11200.00,127177.66,55591.34,30952.82,19000.00,2.93,0.12,0.34
681,318010,팜스빌,7890.00,15700.00,12029.05,1506.40,10250.00,1.17,0.12,0.85
432,021045,대호피앤씨우,1000.00,2880.00,1561.36,247.27,1270.00,1.23,0.12,0.81
150,049120,파인디앤씨,770.00,4190.00,2177.28,509.47,1580.00,1.38,0.12,0.73
45,114120,크루셜텍,618.10,11357.60,4293.93,2772.76,1050.00,4.09,0.12,0.24
447,007820,에스엠코어,6200.00,18318.91,11199.25,3240.46,7410.00,1.51,0.12,0.66
503,227610,아우딘퓨쳐스,1165.00,13850.00,5451.46,2923.69,2035.00,2.68,0.12,0.37
336,045890,GV,271.58,1976.36,738.96,352.41,330.00,2.24,0.12,0.45
736,234920,자이글,1650.00,13050.00,6521.47,2277.47,3905.00,1.67,0.13,0.60
177,091970,나노캠텍,1226.65,5483.77,3236.40,1071.32,2040.00,1.59,0.13,0.63
639,069110,코스온,2350.75,12048.69,6939.40,2542.24,4110.00,1.69,0.13,0.59
76,053980,오상자이엘,5350.00,18100.00,8951.44,2152.34,6590.00,1.36,0.14,0.74
767,340570,티앤엘,36800.00,59300.00,43091.56,4304.33,38400.00,1.12,0.14,0.89
554,014200,광림,1425.00,6808.93,2867.65,1142.55,1645.00,1.74,0.14,0.57
14,064240,홈캐스트,1985.00,18498.31,6644.20,3543.76,2880.00,2.31,0.14,0.43
730,039980,리노스,731.20,3721.74,1824.86,628.44,1160.00,1.57,0.15,0.64
165,079650,서산,1350.00,7080.00,3586.75,979.11,2555.00,1.40,0.15,0.71
145,030350,드래곤플라이,1038.70,7336.63,3590.34,1074.95,2460.00,1.46,0.15,0.69
769,129890,앱코,25100.00,33800.00,28339.86,1993.44,26250.00,1.08,0.15,0.93
18,067080,대화제약,5815.03,33431.52,18512.13,5825.10,12450.00,1.49,0.15,0.67
778,348030,모비릭스,20850.00,36302.19,25081.04,4020.08,20900.00,1.20,0.15,0.83
741,108860,셀바스AI,2360.00,7280.00,4180.14,1119.70,3035.00,1.38,0.15,0.73
546,023160,태광,5670.00,15200.00,10082.73,2238.30,7800.00,1.29,0.15,0.77
196,050120,라이브플렉스,2768.77,11200.06,5642.04,1136.48,4505.00,1.25,0.16,0.80
717,217480,에스디생명공학,2360.00,22098.79,9151.41,4262.02,5020.00,1.82,0.17,0.55
522,066360,체리부로,1140.00,4575.00,2724.53,527.70,2220.00,1.23,0.17,0.81
226,161570,THE MIDONG,1137.31,8222.24,3429.23,1701.60,1810.00,1.89,0.17,0.53
459,047770,코데즈컴바인,1315.00,4145.00,2897.10,442.24,2485.00,1.17,0.18,0.86
85,036000,예림당,1485.00,15300.00,6116.73,3232.53,3105.00,1.97,0.18,0.51
36,222040,코스맥스엔비티,2860.00,29350.00,14445.32,7059.21,8040.00,1.80,0.18,0.56

In [13]:
df[df['Code'] == '003380'].iloc[-1]['Close']

8880.0

In [14]:
df[df['Code'] == '054800'].iloc[-1]['Close']

12900.0

In [15]:
df[df['Code'] == '054950'].iloc[-1]

Date            2021-03-16 00:00:00
Code                         054950
Name                          제이브이엠
Market                       KOSDAQ
Dept                          우량기업부
Close                       36200.0
ChangeCode                        2
Changes                      -100.0
ChagesRatio                     NaN
Open                        36650.0
High                        36650.0
Low                         36150.0
Volume                      35764.0
Amount                 1298677900.0
Marcap               229178869600.0
Stocks                    6330908.0
MarketId                        KSQ
Rank                            872
ChangesRatio                  -0.28
Name: 11192942, dtype: object

In [16]:
wdf[wdf[1]=="파루"]

Empty DataFrame
Columns: [0, 1, 2, 3, 4, 5, 6, 7, 8, C/M]
Index: []