In [45]:
# 우량주 분석
import datetime
# today=  datetime.datetime.now()
today = datetime.datetime.strptime('2021-11-05', '%Y-%m-%d')

first = '1995-05-02'
m6_ago = today - datetime.timedelta(days=183)
y1_ago = today - datetime.timedelta(days=365)
y1_5_ago = today - datetime.timedelta(days=(365+183))
y2_ago = today - datetime.timedelta(days=2*365)
y3_ago  = today  - datetime.timedelta(days=3*365)
y4_ago  = today  - datetime.timedelta(days=4*365)
y5_ago = today - datetime.timedelta(days=5*365)
y6_ago = today - datetime.timedelta(days=6*365)
y7_ago = today - datetime.timedelta(days=7*365)
y8_ago = today - datetime.timedelta(days=8*365)
y10_ago = today - datetime.timedelta(days=10*365)

today = today.strftime('%Y-%m-%d')

m6_ago = m6_ago.strftime('%Y-%m-%d')
y1_ago = y1_ago.strftime('%Y-%m-%d')
y1_5_ago = y1_5_ago.strftime('%Y-%m-%d')
y2_ago = y2_ago.strftime('%Y-%m-%d')
y3_ago = y3_ago.strftime('%Y-%m-%d')
y4_ago = y4_ago.strftime('%Y-%m-%d')
y5_ago = y5_ago.strftime('%Y-%m-%d')
y6_ago = y6_ago.strftime('%Y-%m-%d')
y7_ago = y7_ago.strftime('%Y-%m-%d')


y8_ago = y8_ago.strftime('%Y-%m-%d')
y10_ago = y10_ago.strftime('%Y-%m-%d')
y1_5_ago

'2020-05-06'

In [40]:
# 기본 모듈 로드
import pandas as pd
from marcap import marcap_data
import matplotlib.pyplot as plt

In [41]:
# 그래프 설정
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

years = mdates.YearLocator()   # every year
months = mdates.MonthLocator()  # every month
years_fmt = mdates.DateFormatter('%Y')

plt.rcParams["figure.figsize"] = (16,4)
plt.rcParams['lines.linewidth'] = 0.5
plt.rcParams["axes.grid"] = True
plt.rcParams["axes.formatter.useoffset"] = False
plt.rcParams["xtick.minor.visible"] = True 

pd.options.display.float_format = '{:.2f}'.format

In [20]:
df = marcap_data(first, today)

c:\users\jae\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py:3361: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):
c:\users\jae\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py:3361: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

In [21]:
df['Dept'].unique()
df.reset_index(inplace=True)

In [48]:
df1 = df[df['Date']>y1_ago]
df1_5 = df[df['Date']>y1_5_ago]

df2 = df[df['Date']>y2_ago]
df3 = df[df['Date']>y3_ago]
df4 = df[df['Date']>y4_ago]

df5 = df[df['Date']>y5_ago]
df6 = df[df['Date']>y6_ago]
df7 = df[df['Date']>y7_ago]

df8 = df[df['Date']>y8_ago]
df10 = df[df['Date']>y10_ago]

# df1_10 = df[df['Date']>y10_ago]
# df1_10 = df1_10[df1_10['Date']<y1_ago]
# df1_5 = df[df['Date']>y5_ago]
# df1_5 = df1_5[df1_5['Date']<y1_ago]

In [23]:
dm6 = df[df['Date']>m6_ago]

In [49]:
d = df1_5
d

,Date,Code,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId,Rank,ChangesRatio
10687523,2020-05-07,005930,삼성전자,KOSPI,NaN,48800.00,2,-400.00,-0.81,49200.00,49300.00,48700.00,13884411.00,679668516460.00,291325388440000.00,5969782550.00,STK,1,NaN
10687524,2020-05-07,000660,SK하이닉스,KOSPI,NaN,82400.00,3,0.00,0.00,82400.00,83400.00,81800.00,2660512.00,220302375800.00,59987394876000.00,728002365.00,STK,2,NaN
10687525,2020-05-07,207940,삼성바이오로직스,KOSPI,NaN,567000.00,2,-8000.00,-1.39,571000.00,578000.00,566000.00,138941.00,79249681000.00,37515555000000.00,66165000.00,STK,3,NaN
10687526,2020-05-07,035420,NAVER,KOSPI,NaN,215500.00,1,3500.00,1.65,211500.00,220000.00,210500.00,984024.00,211748985000.00,35398761622500.00,164263395.00,STK,4,NaN
10687527,2020-05-07,005935,삼성전자우,KOSPI,NaN,41600.00,2,-400.00,-0.95,42300.00,42300.00,41600.00,1090970.00,45725726950.00,34232086720000.00,822886700.00,STK,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11586017,2021-11-05,270210,에스알바이오텍,KONEX,일반기업부,4305.00,2,-45.00,NaN,4305.00,4305.00,4305.00,1.00,4305.00,3473308440.00,806808.00,KNX,2588,-1.03
11586018,2021-11-05,245450,씨앤에스링크,KONEX,일반기업부,2190.00,2,-5.00,NaN,2190.00,2190.00,2190.00,1.00,2190.00,3460112400.00,1579960.00,KNX,2589,-0.23
11586019,2021-11-05,001529,동양3우B,KOSPI,NaN,37500.00,2,-400.00,NaN,38700.00,38900.00,36550.00,3623.00,138016700.00,3364575000.00,89722.00,STK,2590,-1.06
11586020,2021-11-05,329020,오션스톤,KONEX,일반기업부,2500.00,3,0.00,NaN,2400.00,2700.00,2135.00,830.00,1840335.00,2000000000.00,800000.00,KNX,2592,0.00
11586021,2021-11-05,267810,앙츠,KONEX,일반기업부,1185.00,2,-175.00,NaN,1495.00,1495.00,1185.00,101.00,119995.00,1833195000.00,1547000.00,KNX,2593,-12.87

In [50]:
wuryang = d[d['Market'] == 'KOSPI']
wuryang

,Date,Code,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId,Rank,ChangesRatio
10687523,2020-05-07,005930,삼성전자,KOSPI,NaN,48800.00,2,-400.00,-0.81,49200.00,49300.00,48700.00,13884411.00,679668516460.00,291325388440000.00,5969782550.00,STK,1,NaN
10687524,2020-05-07,000660,SK하이닉스,KOSPI,NaN,82400.00,3,0.00,0.00,82400.00,83400.00,81800.00,2660512.00,220302375800.00,59987394876000.00,728002365.00,STK,2,NaN
10687525,2020-05-07,207940,삼성바이오로직스,KOSPI,NaN,567000.00,2,-8000.00,-1.39,571000.00,578000.00,566000.00,138941.00,79249681000.00,37515555000000.00,66165000.00,STK,3,NaN
10687526,2020-05-07,035420,NAVER,KOSPI,NaN,215500.00,1,3500.00,1.65,211500.00,220000.00,210500.00,984024.00,211748985000.00,35398761622500.00,164263395.00,STK,4,NaN
10687527,2020-05-07,005935,삼성전자우,KOSPI,NaN,41600.00,2,-400.00,-0.95,42300.00,42300.00,41600.00,1090970.00,45725726950.00,34232086720000.00,822886700.00,STK,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11586007,2021-11-05,001527,동양2우B,KOSPI,NaN,14400.00,2,-350.00,NaN,14600.00,14850.00,14400.00,3592.00,52407850.00,4443393600.00,308569.00,STK,2578,-2.37
11586009,2021-11-05,002787,진흥기업2우B,KOSPI,NaN,14500.00,1,100.00,NaN,14450.00,14500.00,14300.00,453.00,6523750.00,4274716000.00,294808.00,STK,2580,0.69
11586010,2021-11-05,000547,흥국화재2우B,KOSPI,NaN,27800.00,2,-300.00,NaN,27600.00,27850.00,27600.00,192.00,5323000.00,4270080000.00,153600.00,STK,2581,-1.07
11586011,2021-11-05,009275,신원우,KOSPI,NaN,47050.00,2,-450.00,NaN,47100.00,47600.00,46550.00,257.00,12056050.00,4269317000.00,90740.00,STK,2582,-0.95
11586019,2021-11-05,001529,동양3우B,KOSPI,NaN,37500.00,2,-400.00,NaN,38700.00,38900.00,36550.00,3623.00,138016700.00,3364575000.00,89722.00,STK,2590,-1.06

In [51]:
codes = wuryang['Code'].unique()

In [52]:
len(codes)

946

In [53]:
data = list()
import scipy.stats
# for code in codes:


for code in codes:
    c = d[d['Code'] == code]
    if c['Date'].iloc[-1] == pd.to_datetime(today):
        latest_stocks = c['Stocks'].iloc[-1]
        c['Adj Close'] = c['Stocks'] * c['Close'] / latest_stocks

        c_min = c['Adj Close'].min()
        c_max = c['Adj Close'].max()
        c_mean = c['Adj Close'].mean()
        c_std = c['Adj Close'].std()

        c_current = c['Adj Close'].iloc[-1]

        c_norm = scipy.stats.norm(c_mean, c_std)

        data.append([code, c['Name'].iloc[-1], c_min, c_max, c_mean, c_std, c_current, c_mean/c_current, c_norm.cdf(c_current)])

C:\Users\jae\AppData\Local\Temp/ipykernel_8384/4028455208.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c['Adj Close'] = c['Stocks'] * c['Close'] / latest_stocks

In [54]:
columns = ['Code', 'Name', 'Min', 'Max', 'Mean', 'Std', 'Current', 'M/C', 'Cdf']
wdf = pd.DataFrame(data,columns=['Code', 'Name', 'Min', 'Max', 'Mean', 'Std', 'Current', 'M/C', 'Cdf'] )
wdf['C/M'] = 1 / wdf['M/C']
wdf['Max/Current'] = wdf['Max']/wdf['Current']
wdf.sort_values(['Cdf'], ascending=[True]).to_csv('kospi-1.5Y-%s.csv' % today)
wdf.sort_values(['Cdf'], ascending=[True]).head(60)

,Code,Name,Min,Max,Mean,Std,Current,M/C,Cdf,C/M,Max/Current
464,027740,마니커,1815.00,3985.00,3364.21,458.47,1815.00,1.85,0.00,0.54,2.20
91,007310,오뚜기,472500.00,601000.00,551166.61,26521.32,472500.00,1.17,0.00,0.86,1.27
354,234080,JW생명과학,14550.00,24800.00,19160.48,1660.03,15250.00,1.26,0.01,0.80,1.63
7,051900,LG생활건강,1171000.00,1770000.00,1497812.33,116983.76,1229000.00,1.22,0.01,0.82,1.44
116,051905,LG생활건강우,598000.00,805000.00,706898.12,31013.44,636000.00,1.11,0.01,0.90,1.27
206,001630,종근당홀딩스,81500.00,139000.00,108814.48,12139.37,81500.00,1.34,0.01,0.75,1.71
199,001060,JW중외제약,22450.00,40305.72,31198.48,3736.58,22800.00,1.37,0.01,0.73,1.77
643,084670,동양고속,20750.00,31400.00,24901.34,1861.31,20750.00,1.20,0.01,0.83,1.51
229,008490,서흥,43350.00,59700.00,53098.79,3101.57,46200.00,1.15,0.01,0.87,1.29
287,002210,동성제약,8730.00,16600.00,11771.76,1396.86,8730.00,1.35,0.01,0.74,1.90
185,170900,동아에스티,72097.62,107496.45,86209.32,6058.46,73200.00,1.18,0.02,0.85,1.47
477,004840,DRB동일,5510.00,8790.00,6948.77,620.82,5630.00,1.23,0.02,0.81,1.56
520,000520,삼일제약,7770.00,12448.24,9745.22,823.25,8000.00,1.22,0.02,0.82,1.56
119,005690,파미셀,12050.00,24100.00,18043.97,2761.64,12200.00,1.48,0.02,0.68,1.98
55,000120,CJ대한통운,141000.00,189500.00,166380.70,10639.55,144500.00,1.15,0.02,0.87,1.31
671,009310,참엔지니어링,1150.00,1780.00,1445.92,144.88,1150.00,1.26,0.02,0.80,1.55
277,293480,하나제약,19597.20,25886.54,21969.96,1021.16,19900.00,1.10,0.02,0.91,1.30
296,096760,JW홀딩스,3510.00,6233.42,4983.33,591.87,3785.00,1.32,0.02,0.76,1.65
379,322000,현대에너지솔루션,20450.00,43850.00,31990.62,5236.68,21600.00,1.48,0.02,0.68,2.03
693,006570,대림통상,3610.00,5290.00,4147.29,222.13,3710.00,1.12,0.02,0.89,1.43
16,036570,엔씨소프트,558000.00,1038000.00,824613.94,102839.37,624000.00,1.32,0.03,0.76,1.66
5,068270,셀트리온,199226.23,394908.66,281409.64,37277.57,209000.00,1.35,0.03,0.74,1.89
397,214420,토니모리,6190.00,11466.56,8733.35,1113.27,6580.00,1.33,0.03,0.75,1.74
109,003000,부광약품,12450.00,37910.25,23939.01,5517.85,13300.00,1.80,0.03,0.56,2.85
694,00499K,롯데지주우,49300.00,88400.00,62005.36,5477.68,51500.00,1.20,0.03,0.83,1.72
213,002320,한진,33200.00,51100.00,40925.01,4111.80,33200.00,1.23,0.03,0.81,1.54
904,950210,프레스티지바이오파마,22400.00,50000.00,30786.22,4466.02,22400.00,1.37,0.03,0.73,2.23
204,008350,남선알미늄,2870.00,6640.00,4479.44,859.29,2870.00,1.56,0.03,0.64,2.31
384,004710,한솔테크닉스,6460.00,11650.00,8854.85,1239.30,6540.00,1.35,0.03,0.74,1.78
17,018260,삼성에스디에스,150000.00,219500.00,179210.46,12049.21,157000.00,1.14,0.03,0.88,1.40
66,012510,더존비즈온,76094.36,123543.54,97642.24,9889.96,79700.00,1.23,0.03,0.82,1.55
481,021050,서원,2005.00,4425.00,2920.59,469.63,2070.00,1.41,0.04,0.71,2.14
224,003060,에이프로젠제약,921.58,1615.00,1238.74,135.27,1000.00,1.24,0.04,0.81,1.61
487,002795,아모레G우,17000.00,28600.00,22131.10,2437.42,17850.00,1.24,0.04,0.81,1.60
153,042670,현대두산인프라코어,8100.00,48895.83,21837.27,7845.01,8100.00,2.70,0.04,0.37,6.04
805,18064K,한진칼우,36300.00,69400.00,45943.16,5569.38,36300.00,1.27,0.04,0.79,1.91
926,381970,케이카,23000.00,25850.00,24500.00,782.91,23150.00,1.06,0.04,0.94,1.12
177,001680,대상,23000.00,30700.00,26236.33,1438.23,23800.00,1.10,0.05,0.91,1.29
355,123690,한국화장품,8990.00,16800.00,12439.84,1482.76,9930.00,1.25,0.05,0.80,1.69
616,002140,고려산업,2920.00,5030.00,3989.01,393.72,3335.00,1.20,0.05,0.84,1.51
424,003350,한국화장품제조,27000.00,48000.00,36712.60,3848.68,30350.00,1.21,0.05,0.83,1.58
237,006060,화승인더,6400.00,9430.00,7502.31,583.59,6540.00,1.15,0.05,0.87,1.44
911,383800,LX홀딩스,8710.00,12250.00,10204.59,851.97,8810.00,1.16,0.05,0.86,1.39
348,003120,일성신약,76000.00,96600.00,82784.72,3760.36,76700.00,1.08,0.05,0.93,1.26
438,015590,큐로,492.00,778.65,606.44,63.11,506.00,1.20,0.06,0.83,1.54
498,007540,샘표,42800.00,71600.00,52057.91,5254.75,43750.00,1.19,0.06,0.84,1.64
303,002390,한독,23100.00,40850.00,29475.87,3780.21,23500.00,1.25,0.06,0.80,1.74
195,071840,롯데하이마트,26700.00,43400.00,33737.27,4208.61,27150.00,1.24,0.06,0.80,1.60
495,078000,텔코웨어,10800.00,14050.00,12088.47,604.16,11150.00,1.08,0.06,0.92,1.26
709,033250,체시스,1241.25,2508.75,1758.09,282.85,1320.00,1.33,0.06,0.75,1.90
504,002720,국제약품,5890.00,13936.83,8403.91,1650.74,5890.00,1.43,0.06,0.70,2.37
373,002620,제일파마홀딩스,14550.00,31000.00,21376.94,2751.54,17200.00,1.24,0.06,0.80,1.80
338,012690,모나리자,3725.00,7840.00,5313.66,769.60,4155.00,1.28,0.07,0.78,1.89
839,008355,남선알미우,23300.00,104000.00,48177.75,16525.92,23300.00,2.07,0.07,0.48,4.46
183,034310,NICE,16700.00,22700.00,18877.35,1283.04,16950.00,1.11,0.07,0.90,1.34
908,361610,SK아이이테크놀로지,138000.00,235500.00,189311.48,30075.68,145500.00,1.30,0.07,0.77,1.62
102,009240,한샘,72100.00,146500.00,104593.30,10353.04,89600.00,1.17,0.07,0.86,1.64
910,380440,엔에이치스팩19호,2085.00,2470.00,2186.78,60.71,2100.00,1.04,0.08,0.96,1.18
509,143210,핸즈코퍼레이션,5290.00,9580.00,6740.19,852.92,5540.00,1.22,0.08,0.82,1.73
463,011150,CJ씨푸드,3410.00,6080.00,4495.12,512.18,3780.00,1.19,0.08,0.84,1.61

In [30]:
df[df['Code'] == '003380'].iloc[-1]['Close']

9190.0

In [31]:
df[df['Code'] == '054800'].iloc[-1]['Close']

12750.0

In [32]:
df[df['Code'] == '054950'].iloc[-1]

Date            2021-11-05 00:00:00
Code                         054950
Name                          제이브이엠
Market                       KOSDAQ
Dept                          우량기업부
Close                      15000.00
ChangeCode                        3
Changes                        0.00
ChagesRatio                     NaN
Open                       15200.00
High                       15250.00
Low                        14700.00
Volume                     46969.00
Amount                 698260400.00
Marcap              181348380000.00
Stocks                  12089892.00
MarketId                        KSQ
Rank                           1147
ChangesRatio                   0.00
Name: 11584677, dtype: object