In [1]:
# 우량주 분석
import datetime
# today=  datetime.datetime.now()
today = datetime.datetime.strptime('2021-03-29', '%Y-%m-%d')

first = '1995-05-02'
m6_ago = today - datetime.timedelta(days=183)
y1_ago = today - datetime.timedelta(days=365)
y2_ago = today - datetime.timedelta(days=2*365)
y3_ago  = today  - datetime.timedelta(days=3*365)
y4_ago  = today  - datetime.timedelta(days=4*365)
y5_ago = today - datetime.timedelta(days=5*365)
y6_ago = today - datetime.timedelta(days=6*365)

y8_ago = today - datetime.timedelta(days=8*365)
y10_ago = today - datetime.timedelta(days=10*365)

today = today.strftime('%Y-%m-%d')

m6_ago = m6_ago.strftime('%Y-%m-%d')
y1_ago = y1_ago.strftime('%Y-%m-%d')
y2_ago = y2_ago.strftime('%Y-%m-%d')
y3_ago = y3_ago.strftime('%Y-%m-%d')
y4_ago = y4_ago.strftime('%Y-%m-%d')
y5_ago = y5_ago.strftime('%Y-%m-%d')
y6_ago = y6_ago.strftime('%Y-%m-%d')

y8_ago = y8_ago.strftime('%Y-%m-%d')
y10_ago = y10_ago.strftime('%Y-%m-%d')
y1_ago

'2020-03-29'

In [2]:
# 기본 모듈 로드
import pandas as pd
from marcap import marcap_data
import matplotlib.pyplot as plt

In [3]:
# 그래프 설정
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

years = mdates.YearLocator()   # every year
months = mdates.MonthLocator()  # every month
years_fmt = mdates.DateFormatter('%Y')

plt.rcParams["figure.figsize"] = (16,4)
plt.rcParams['lines.linewidth'] = 0.5
plt.rcParams["axes.grid"] = True
plt.rcParams["axes.formatter.useoffset"] = False
plt.rcParams["xtick.minor.visible"] = True 

pd.options.display.float_format = '{:.2f}'.format

In [4]:
nps = pd.read_csv('NPS.csv')
# nps = nps[nps['Share'] > 1]

In [5]:
df = marcap_data(first, today)

c:\users\j\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py:3338: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):
c:\users\j\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py:3338: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

In [6]:
df['Dept'].unique()
df.reset_index(inplace=True)

In [7]:
df1 = df[df['Date']>y1_ago]
df2 = df[df['Date']>y2_ago]
df3 = df[df['Date']>y3_ago]
df4 = df[df['Date']>y4_ago]

df5 = df[df['Date']>y5_ago]
df6 = df[df['Date']>y6_ago]

df8 = df[df['Date']>y8_ago]
df10 = df[df['Date']>y10_ago]

df1_10 = df[df['Date']>y10_ago]
df1_10 = df1_10[df1_10['Date']<y1_ago]
df1_5 = df[df['Date']>y5_ago]
df1_5 = df1_5[df1_5['Date']<y1_ago]

In [8]:
dm6 = df[df['Date']>m6_ago]

In [9]:
d = df5

In [10]:
names = nps['Name'].unique()
len(names)

1066

In [11]:
data = list()
import scipy.stats
# for code in codes:


for name in names:
    try:
        c = d[d['Name'] == name]
        if c['Date'].iloc[-1] == pd.to_datetime(today):
            latest_stocks = c['Stocks'].iloc[-1]
            code = c['Code'].iloc[-1]
            c['Adj Close'] = c['Stocks'] * c['Close'] / latest_stocks

            c_min = c['Adj Close'].min()
            c_max = c['Adj Close'].max()
            c_mean = c['Adj Close'].mean()
            c_std = c['Adj Close'].std()

            c_current = c['Adj Close'].iloc[-1]

            c_norm = scipy.stats.norm(c_mean, c_std)

            data.append([code, c['Name'].iloc[-1], c_min, c_max, c_mean, c_std, c_current, c_mean/c_current, c_norm.cdf(c_current)])
    except:
        print(name)

<ipython-input-11-30f1e31a3092>:12: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c['Adj Close'] = c['Stocks'] * c['Close'] / latest_stocks

CJ4우
아모레G3우
서부티엔디
제이더블유홀딩스
MTRON

In [12]:
columns = ['Code', 'Name', 'Min', 'Max', 'Mean', 'Std', 'Current', 'M/C', 'Cdf']
wdf = pd.DataFrame(data)
wdf['C/M'] = 1 / wdf[7]
wdf['Max/Current'] = wdf[3]/wdf[6]
wdf.sort_values([8], ascending=[True]).to_csv('NPS-%s.csv' % today)
wdf.sort_values([8], ascending=[True]).head(60)

,0,1,2,3,4,5,6,7,8,C/M,Max/Current
973,019685,대교우B,2175.00,5690.00,4356.48,999.67,2610.00,1.67,0.04,0.60,2.18
73,012750,에스원,73800.00,115000.00,94006.61,6930.25,82300.00,1.14,0.05,0.88,1.40
745,000155,두산우,25800.00,92604.19,69517.34,18150.87,39400.00,1.76,0.05,0.57,2.35
632,041960,코미팜,10000.00,42600.99,23449.16,7913.34,10650.00,2.20,0.05,0.45,4.00
448,007980,태평양물산,1129.89,4659.29,2933.53,677.57,1840.00,1.59,0.05,0.63,2.53
304,115450,지트리비앤티,11700.00,47158.66,23071.42,7087.28,11700.00,1.97,0.05,0.51,4.03
15,033780,KT&G,63600.00,137000.00,100888.01,13108.29,80200.00,1.26,0.06,0.79,1.71
24,000810,삼성화재,126000.00,309000.00,251202.28,40794.65,187000.00,1.34,0.06,0.74,1.65
300,003920,남양유업,255000.00,944000.00,575616.23,174517.34,301000.00,1.91,0.06,0.52,3.14
334,019680,대교,3075.00,11000.00,6786.82,1710.58,4190.00,1.62,0.06,0.62,2.63
977,025560,미래산업,2494.02,14331.46,7011.32,2589.34,3150.00,2.23,0.07,0.45,4.55
819,091090,세원셀론텍,1282.00,5816.32,2807.91,677.03,1815.00,1.55,0.07,0.65,3.20
400,096760,JW홀딩스,3592.47,15198.91,7059.58,1817.98,4400.00,1.60,0.07,0.62,3.45
157,000150,두산,26050.00,177326.56,107525.17,39275.03,50200.00,2.14,0.07,0.47,3.53
970,084670,동양고속,20856.51,36502.02,28909.26,3524.14,23850.00,1.21,0.08,0.82,1.53
561,078520,에이블씨엔씨,5790.00,21617.33,12272.75,3405.20,7430.00,1.65,0.08,0.61,2.91
318,002960,한국쉘석유,206000.00,501000.00,348099.10,69409.50,250500.00,1.39,0.08,0.72,2.00
923,034590,인천도시가스,20950.00,32050.00,28908.16,2282.29,25700.00,1.12,0.08,0.89,1.25
479,007660,이수페타시스,1785.00,7070.00,4497.46,814.34,3355.00,1.34,0.08,0.75,2.11
757,026040,제이에스티나,1390.00,14850.00,6163.38,2914.81,2075.00,2.97,0.08,0.34,7.16
350,071320,지역난방공사,26000.00,87400.00,58572.92,14711.95,37950.00,1.54,0.08,0.65,2.30
231,086900,메디톡스,104900.00,807677.76,409307.35,156333.13,191300.00,2.14,0.08,0.47,4.22
505,001130,대한제분,91500.00,240500.00,171931.48,20202.99,144500.00,1.19,0.09,0.84,1.66
236,009970,영원무역홀딩스,27400.00,72000.00,52694.82,9312.98,40150.00,1.31,0.09,0.76,1.79
640,378850,화승알앤에이,3908.96,15516.89,8581.28,2486.66,5350.00,1.60,0.10,0.62,2.90
42,078930,GS,30300.00,76700.00,51559.42,9937.96,38850.00,1.33,0.10,0.75,1.97
764,062970,피피아이,3800.00,13400.00,8176.05,1851.04,5830.00,1.40,0.10,0.71,2.30
536,015360,예스코홀딩스,26300.00,42800.00,37704.20,3288.95,33550.00,1.12,0.10,0.89,1.28
295,005500,삼진제약,16650.00,58200.00,33359.54,7412.98,24000.00,1.39,0.10,0.72,2.42
283,017940,E1,22400.00,74000.00,55106.44,9715.44,42850.00,1.29,0.10,0.78,1.73
773,014990,인디에프,926.00,4300.00,2075.96,636.03,1275.00,1.63,0.10,0.61,3.37
433,004970,신라교역,6850.00,17800.00,13443.19,2378.92,10450.00,1.29,0.10,0.78,1.70
593,005720,넥센,2985.00,8694.79,6357.56,1383.80,4620.00,1.38,0.10,0.73,1.88
855,260930,씨티케이코스메틱스,8850.00,46000.00,21035.55,8716.59,10100.00,2.08,0.10,0.48,4.55
752,255440,야스,7510.00,31141.71,19424.12,5035.48,13150.00,1.48,0.11,0.68,2.37
355,035000,지투알,3400.00,11600.00,7743.24,1688.49,5670.00,1.37,0.11,0.73,2.05
424,000850,화천기공,23950.00,62900.00,45117.78,9271.03,33800.00,1.33,0.11,0.75,1.86
172,000815,삼성화재우,86100.00,206500.00,170853.83,21975.75,144500.00,1.18,0.12,0.85,1.43
327,029530,신도리코,19500.00,73100.00,45772.72,13005.98,30250.00,1.51,0.12,0.66,2.42
747,040420,정상제이엘에스,5440.00,8450.00,7155.89,604.91,6440.00,1.11,0.12,0.90,1.31
770,214420,토니모리,6300.00,37666.67,15966.19,6794.16,7930.00,2.01,0.12,0.50,4.75
599,005800,신영와코루,64300.00,189000.00,130507.59,28317.57,97100.00,1.34,0.12,0.74,1.95
261,006840,AK홀딩스,12000.00,86900.00,50508.93,19711.13,27650.00,1.83,0.12,0.55,3.14
384,002795,아모레G우,16100.00,85600.00,43420.80,18722.97,21850.00,1.99,0.12,0.50,3.92
343,053210,스카이라이프,4760.00,18500.00,12402.21,3284.03,8620.00,1.44,0.12,0.70,2.15
330,004690,삼천리,56000.00,125500.00,96367.46,14753.75,79500.00,1.21,0.13,0.82,1.58
418,033920,무학,3660.00,35544.04,15246.47,7301.20,6900.00,2.21,0.13,0.45,5.15
84,001450,현대해상,17700.00,49200.00,32831.65,7713.78,24050.00,1.37,0.13,0.73,2.05
485,004150,한솔홀딩스,2414.86,9075.36,5469.47,1516.47,3745.00,1.46,0.13,0.68,2.42
370,101060,SBS미디어홀딩스,1575.00,3500.00,2462.96,482.16,1915.00,1.29,0.13,0.78,1.83
870,003120,일성신약,76000.00,151000.00,103906.28,19476.74,81800.00,1.27,0.13,0.79,1.85
650,225190,삼양옵틱스,7497.99,19717.22,13494.95,3112.75,10000.00,1.35,0.13,0.74,1.97
792,067080,대화제약,5815.03,46990.13,21074.96,8295.94,11800.00,1.79,0.13,0.56,3.98
768,025620,제이준코스메틱,1326.59,20019.49,7336.51,4859.54,1905.00,3.85,0.13,0.26,10.51
624,070960,용평리조트,2450.00,14000.00,7480.62,2524.18,4665.00,1.60,0.13,0.62,3.00
239,002270,롯데푸드,211500.00,1128825.56,618986.63,214049.17,380500.00,1.63,0.13,0.61,2.97
100,114090,GKL,10900.00,34000.00,21617.78,4797.22,16300.00,1.33,0.13,0.75,2.09
838,002360,SH에너지화학,507.00,1960.00,1255.64,296.48,928.00,1.35,0.13,0.74,2.11
636,090470,제이스텍,5230.00,28450.00,12881.92,5241.35,7140.00,1.80,0.14,0.55,3.98
999,002355,넥센타이어1우B,1730.00,6490.00,4351.72,1310.56,2930.00,1.49,0.14,0.67,2.22

In [13]:
len(data)

1011

In [14]:
df[df['Code'] == '054800'].iloc[-1]['Close']

13050.0

In [15]:
df[df['Code'] == '054950'].iloc[-1]

Date            2021-03-29 00:00:00
Code                         054950
Name                          제이브이엠
Market                       KOSDAQ
Dept                          우량기업부
Close                       37700.0
ChangeCode                        1
Changes                       100.0
ChagesRatio                     NaN
Open                        37100.0
High                        37800.0
Low                         37050.0
Volume                      74471.0
Amount                 2788435600.0
Marcap               238675231600.0
Stocks                    6330908.0
MarketId                        KSQ
Rank                            864
ChangesRatio                   0.27
Name: 11214866, dtype: object