In [1]:
# 우량주 분석
import datetime
today=  datetime.datetime.now()

first = '1995-05-02'

y1_ago = today - datetime.timedelta(days=365)
y2_ago = today - datetime.timedelta(days=2*365)
y3_ago  = today  - datetime.timedelta(days=3*365)
y4_ago  = today  - datetime.timedelta(days=4*365)
y5_ago = today - datetime.timedelta(days=5*365)
y8_ago = today - datetime.timedelta(days=8*365)
y10_ago = today - datetime.timedelta(days=10*365)

today = today.strftime('%Y-%m-%d')

y1_ago = y1_ago.strftime('%Y-%m-%d')
y2_ago = y2_ago.strftime('%Y-%m-%d')
y3_ago = y3_ago.strftime('%Y-%m-%d')
y4_ago = y4_ago.strftime('%Y-%m-%d')
y5_ago = y5_ago.strftime('%Y-%m-%d')
y8_ago = y8_ago.strftime('%Y-%m-%d')
y10_ago = y10_ago.strftime('%Y-%m-%d')
y1_ago

'2020-03-11'

In [2]:
# 기본 모듈 로드
import pandas as pd
from marcap import marcap_data
import matplotlib.pyplot as plt

In [3]:
# 그래프 설정
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

years = mdates.YearLocator()   # every year
months = mdates.MonthLocator()  # every month
years_fmt = mdates.DateFormatter('%Y')

plt.rcParams["figure.figsize"] = (16,4)
plt.rcParams['lines.linewidth'] = 0.5
plt.rcParams["axes.grid"] = True
plt.rcParams["axes.formatter.useoffset"] = False
plt.rcParams["xtick.minor.visible"] = True 

pd.options.display.float_format = '{:.2f}'.format

In [4]:
df = marcap_data(first, today)

c:\users\j\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py:3338: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):
c:\users\j\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py:3338: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

In [5]:
df['Dept'].unique()
df.reset_index(inplace=True)

In [6]:
df1 = df[df['Date']>y1_ago]
df2 = df[df['Date']>y2_ago]
df3 = df[df['Date']>y3_ago]
df4 = df[df['Date']>y4_ago]

df5 = df[df['Date']>y5_ago]
df8 = df[df['Date']>y8_ago]
df10 = df[df['Date']>y10_ago]

df1_10 = df[df['Date']>y10_ago]
df1_10 = df1_10[df1_10['Date']<y1_ago]
df1_5 = df[df['Date']>y5_ago]
df1_5 = df1_5[df1_5['Date']<y1_ago]

In [16]:
d = df5

In [17]:
wuryang = d[d['Dept'] == '우량기업부']

In [18]:
codes = wuryang['Code'].unique()

In [19]:
len(codes)

568

In [20]:
data = list()
import scipy.stats
# for code in codes:


for code in codes:
    c = d[d['Code'] == code]
    if c['Date'].iloc[-1] == pd.to_datetime(today):
        latest_stocks = c['Stocks'].iloc[-1]
        c['Adj Close'] = c['Stocks'] * c['Close'] / latest_stocks

        c_min = c['Adj Close'].min()
        c_max = c['Adj Close'].max()
        c_mean = c['Adj Close'].mean()
        c_std = c['Adj Close'].std()

        c_current = c['Adj Close'].iloc[-1]

        c_norm = scipy.stats.norm(c_mean, c_std)

        data.append([code, c['Name'].iloc[-1], c_min, c_max, c_mean, c_std, c_current, c_mean/c_current, c_norm.cdf(c_current)])

<ipython-input-20-3ff44c464998>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c['Adj Close'] = c['Stocks'] * c['Close'] / latest_stocks

In [12]:
columns = ['Code', 'Name', 'Min', 'Max', 'Mean', 'Std', 'Current', 'M/C' 'Cdf']
wdf = pd.DataFrame(data)
wdf['C/M'] = 1 / wdf[7]
wdf.sort_values([8], ascending=[True]).head(60)

,0,1,2,3,4,5,6,7,8,C/M
335,043200,파루,1403.49,4759.95,2525.65,461.84,1465.00,1.72,0.01,0.58
53,016250,SGC이테크건설,49350.00,279755.13,180296.05,60390.69,49850.00,3.62,0.02,0.28
213,069410,엔텔스,4890.00,18650.00,11922.29,2305.00,7750.00,1.54,0.04,0.65
437,006620,동구바이오제약,10900.00,43850.00,22466.11,6634.67,10900.00,2.06,0.04,0.49
222,099440,스맥,1082.51,3853.91,2634.05,618.59,1680.00,1.57,0.06,0.64
182,040420,정상제이엘에스,5440.00,8160.00,7143.02,594.10,6230.00,1.15,0.06,0.87
309,060560,홈센타홀딩스,896.00,3085.35,1526.34,376.24,954.00,1.60,0.06,0.63
173,026040,제이에스티나,1390.00,11150.00,5405.18,2312.75,2005.00,2.70,0.07,0.37
191,046070,코다코,974.00,3840.00,2428.07,803.19,1265.00,1.92,0.07,0.52
180,049520,유아이엘,3485.00,8200.00,5280.99,1175.10,3595.00,1.47,0.08,0.68
380,225190,삼양옵틱스,7497.99,19717.22,13548.01,3097.39,9110.00,1.49,0.08,0.67
303,037950,엘컴텍,1225.00,3015.00,1958.91,356.89,1450.00,1.35,0.08,0.74
72,014620,성광벤드,4095.00,14150.00,9816.67,1957.85,7120.00,1.38,0.08,0.73
475,021045,대호피앤씨우,1000.00,2880.00,1568.31,260.46,1215.00,1.29,0.09,0.77
364,255440,야스,7510.00,31141.71,19512.41,5016.18,12800.00,1.52,0.09,0.66
93,007820,에스엠코어,6200.00,18318.91,11220.36,3232.90,7100.00,1.58,0.10,0.63
2,086900,메디톡스,104900.00,807677.76,414530.39,172222.17,197200.00,2.10,0.10,0.48
174,009300,삼아제약,9860.00,31750.00,17667.38,2545.19,14500.00,1.22,0.11,0.82
215,076610,해성옵틱스,792.15,3706.16,1982.46,605.06,1230.00,1.61,0.11,0.62
444,227610,아우딘퓨쳐스,1165.00,13850.00,5463.12,2921.59,1870.00,2.92,0.11,0.34
357,016100,리더스코스메틱,2128.07,24407.73,10671.43,5972.74,3450.00,3.09,0.11,0.32
13,102940,코오롱생명과학,11200.00,127177.66,55782.52,30873.77,18550.00,3.01,0.11,0.33
355,067080,대화제약,5815.03,33431.52,18538.45,5809.49,11650.00,1.59,0.12,0.63
179,093190,빅솔론,3504.46,7395.95,5711.43,865.83,4695.00,1.22,0.12,0.82
319,234920,자이글,1650.00,13050.00,6536.86,2272.76,3900.00,1.68,0.12,0.60
300,069110,코스온,2350.75,12048.69,6955.43,2536.99,4075.00,1.71,0.13,0.59
102,052330,코텍,6900.00,18300.00,13021.16,2723.52,9980.00,1.30,0.13,0.77
162,039980,리노스,731.20,3721.74,1834.83,636.39,1130.00,1.62,0.13,0.62
62,014200,광림,1425.00,6808.93,2888.47,1163.96,1610.00,1.79,0.14,0.56
86,023160,태광,5670.00,15200.00,10088.62,2232.34,7660.00,1.32,0.14,0.76
295,064240,홈캐스트,1985.00,18498.31,6681.14,3551.62,2830.00,2.36,0.14,0.42
283,119610,인터로조,16710.35,44158.12,27438.54,6071.17,20900.00,1.31,0.14,0.76
287,090470,제이스텍,5230.00,28450.00,12437.56,5092.05,7020.00,1.77,0.14,0.56
225,011560,세보엠이씨,3350.00,17300.00,9300.65,2938.80,6220.00,1.50,0.15,0.67
459,066360,체리부로,1140.00,4575.00,2726.32,527.86,2200.00,1.24,0.16,0.81
49,038540,상상인,4750.00,27357.14,11844.30,5373.91,6490.00,1.83,0.16,0.55
358,217480,에스디생명공학,2360.00,22098.79,9169.76,4252.10,4950.00,1.85,0.16,0.54
373,241710,코스메카코리아,5990.00,41400.00,22682.69,9434.58,13350.00,1.70,0.16,0.59
91,084110,휴온스글로벌,17909.92,70335.33,37471.90,10542.99,27250.00,1.38,0.17,0.73
310,065510,휴비츠,5400.00,14748.76,10114.21,2401.13,7800.00,1.30,0.17,0.77
151,004650,창해에탄올,8880.00,22000.00,14743.62,2172.69,12650.00,1.17,0.17,0.86
356,049960,쎌바이오텍,10050.00,52100.00,27926.43,10506.43,18200.00,1.53,0.18,0.65
432,200670,휴메딕스,10650.00,43592.62,27023.70,5476.25,22000.00,1.23,0.18,0.81
281,222040,코스맥스엔비티,2860.00,29350.00,14460.14,7043.49,8060.00,1.79,0.18,0.56
61,035810,이지홀딩스,2321.65,9869.61,6076.83,1302.59,4915.00,1.24,0.19,0.81
443,007680,대원,5949.80,19443.75,10615.66,1594.04,9200.00,1.15,0.19,0.87
73,013030,하이록코리아,6800.00,32900.00,19138.52,4904.22,14800.00,1.29,0.19,0.77
136,007720,대명소노시즌,728.00,3750.00,2016.02,729.93,1375.00,1.47,0.19,0.68
289,228850,레이언스,7210.00,21800.00,15363.40,3405.14,12400.00,1.24,0.19,0.81
98,018120,진로발효,21100.00,41988.64,33626.20,3250.29,30850.00,1.09,0.20,0.92
354,041830,인바디,13500.00,50600.00,25375.00,7817.28,18700.00,1.36,0.20,0.74
491,148150,세경하이테크,14081.74,39550.00,25054.43,5414.53,20500.00,1.22,0.20,0.82
351,267980,매일유업,56600.00,101500.00,77981.92,8777.92,70600.00,1.10,0.20,0.91
509,289010,아이스크림에듀,6160.00,13300.00,8734.88,1159.73,7760.00,1.13,0.20,0.89
343,08537M,루트로닉3우C,7321.09,90978.23,36386.01,27442.46,13450.00,2.71,0.20,0.37
284,051500,CJ프레시웨이,11700.00,47250.00,28778.88,7922.45,22200.00,1.30,0.20,0.77
347,049950,미래컴퍼니,10761.84,150476.01,57701.89,31393.43,31900.00,1.81,0.21,0.55
5,028150,GS홈쇼핑,88600.00,245200.00,172704.18,36628.91,143200.00,1.21,0.21,0.83
235,039310,세중,1100.00,4820.00,3238.21,633.25,2740.00,1.18,0.22,0.85
171,053350,이니텍,2770.00,10700.00,6033.22,1412.62,4925.00,1.23,0.22,0.82

In [13]:
df[df['Code'] == '003380'].iloc[-1]['Close']

8900.0

In [14]:
df[df['Code'] == '054800'].iloc[-1]['Close']

12850.0

In [15]:
df[df['Code'] == '054950'].iloc[-1]

Date            2021-03-11 00:00:00
Code                         054950
Name                          제이브이엠
Market                       KOSDAQ
Dept                          우량기업부
Close                       35350.0
ChangeCode                        1
Changes                       600.0
ChagesRatio                     NaN
Open                        34850.0
High                        35650.0
Low                         34650.0
Volume                      69185.0
Amount                 2437290200.0
Marcap               223797597800.0
Stocks                    6330908.0
MarketId                        KSQ
Rank                            869
ChangesRatio                   1.73
Name: 11185633, dtype: object

In [21]:
df

,Date,Code,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId,Rank,ChangesRatio
0,1995-05-02,15760,한국전력공사,KOSPI,NaN,27400.00,2,-400.00,-1.44,27600.00,27800.00,27400.00,118190.00,3255694000.00,16872679291000.00,615791215.00,STK,1,NaN
1,1995-05-02,5930,삼성전자,KOSPI,NaN,119500.00,2,-1000.00,-0.83,121000.00,121000.00,118500.00,139560.00,16676735000.00,6497053077500.00,54368645.00,STK,2,NaN
2,1995-05-02,5490,포항종합제철,KOSPI,NaN,65500.00,2,-300.00,-0.46,65800.00,66200.00,65400.00,65970.00,4334472000.00,6150568555000.00,93901810.00,STK,3,NaN
3,1995-05-02,200,대우중공업,KOSPI,NaN,9800.00,1,300.00,3.16,9500.00,9840.00,9500.00,288380.00,2805133500.00,3500638978200.00,357208059.00,STK,4,NaN
4,1995-05-02,2610,엘지전자,KOSPI,NaN,31700.00,2,-300.00,-0.94,32000.00,32000.00,31700.00,171460.00,5452050000.00,2521027012200.00,79527666.00,STK,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11187197,2021-03-11,009275,신원우,KOSPI,NaN,31200.00,2,-50.00,NaN,31400.00,31400.00,31100.00,164.00,5114500.00,2831088000.00,90740.00,STK,2545,-0.16
11187198,2021-03-11,224020,에스케이씨에스,KONEX,일반기업부,910.00,3,0.00,NaN,909.00,910.00,909.00,320.00,291000.00,2798250000.00,3075000.00,KNX,2546,0.00
11187199,2021-03-11,001529,동양3우B,KOSPI,NaN,24350.00,2,-100.00,NaN,24450.00,24450.00,23600.00,764.00,18500700.00,2184730700.00,89722.00,STK,2547,-0.41
11187200,2021-03-11,225850,미애부,KONEX,일반기업부,350.00,2,-61.00,NaN,350.00,350.00,350.00,5309.00,1858150.00,1166316550.00,3332333.00,KNX,2549,-14.84
11187201,2021-03-11,225860,엠앤씨생명과학,KONEX,일반기업부,70.00,1,2.00,NaN,73.00,73.00,70.00,12122.00,871856.00,795066440.00,11358092.00,KNX,2550,2.94