In [1]:
# 우량주 분석
import datetime
# today=  datetime.datetime.now()
today = datetime.datetime.strptime('2021-03-29', '%Y-%m-%d')

first = '1995-05-02'

y1_ago = today - datetime.timedelta(days=365)
y2_ago = today - datetime.timedelta(days=2*365)
y3_ago  = today  - datetime.timedelta(days=3*365)
y4_ago  = today  - datetime.timedelta(days=4*365)
y5_ago = today - datetime.timedelta(days=5*365)
y6_ago = today - datetime.timedelta(days=6*365)
y8_ago = today - datetime.timedelta(days=8*365)
y10_ago = today - datetime.timedelta(days=10*365)

today = today.strftime('%Y-%m-%d')

y1_ago = y1_ago.strftime('%Y-%m-%d')
y2_ago = y2_ago.strftime('%Y-%m-%d')
y3_ago = y3_ago.strftime('%Y-%m-%d')
y4_ago = y4_ago.strftime('%Y-%m-%d')
y5_ago = y5_ago.strftime('%Y-%m-%d')
y6_ago = y6_ago.strftime('%Y-%m-%d')
y8_ago = y8_ago.strftime('%Y-%m-%d')
y10_ago = y10_ago.strftime('%Y-%m-%d')
y1_ago

'2020-03-29'

In [2]:
# 기본 모듈 로드
import pandas as pd
from marcap import marcap_data
import matplotlib.pyplot as plt

In [3]:
# 그래프 설정
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

years = mdates.YearLocator()   # every year
months = mdates.MonthLocator()  # every month
years_fmt = mdates.DateFormatter('%Y')

plt.rcParams["figure.figsize"] = (16,4)
plt.rcParams['lines.linewidth'] = 0.5
plt.rcParams["axes.grid"] = True
plt.rcParams["axes.formatter.useoffset"] = False
plt.rcParams["xtick.minor.visible"] = True 

pd.options.display.float_format = '{:.2f}'.format

In [4]:
df = marcap_data(first, today)

c:\users\j\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py:3338: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):
c:\users\j\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py:3338: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

In [5]:
df['Dept'].unique()
df.reset_index(inplace=True)

In [6]:
df1 = df[df['Date']>y1_ago]
df2 = df[df['Date']>y2_ago]
df3 = df[df['Date']>y3_ago]
df4 = df[df['Date']>y4_ago]

df5 = df[df['Date']>y5_ago]
df6 = df[df['Date']>y6_ago]

df8 = df[df['Date']>y8_ago]
df10 = df[df['Date']>y10_ago]

df1_10 = df[df['Date']>y10_ago]
df1_10 = df1_10[df1_10['Date']<y1_ago]
df1_5 = df[df['Date']>y5_ago]
df1_5 = df1_5[df1_5['Date']<y1_ago]

In [7]:
d = df5

In [8]:
wuryang = d[d['Dept'] == '우량기업부']

In [9]:
codes = wuryang['Code'].unique()

In [10]:
len(codes)

567

In [11]:
data = list()
import scipy.stats
# for code in codes:


for code in codes:
    c = d[d['Code'] == code]
    if c['Date'].iloc[-1] == pd.to_datetime(today):
        latest_stocks = c['Stocks'].iloc[-1]
        c['Adj Close'] = c['Stocks'] * c['Close'] / latest_stocks

        c_min = c['Adj Close'].min()
        c_max = c['Adj Close'].max()
        c_mean = c['Adj Close'].mean()
        c_std = c['Adj Close'].std()

        c_current = c['Adj Close'].iloc[-1]

        c_norm = scipy.stats.norm(c_mean, c_std)

        data.append([code, c['Name'].iloc[-1], c_min, c_max, c_mean, c_std, c_current, c_mean/c_current, c_norm.cdf(c_current)])

<ipython-input-11-3ff44c464998>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c['Adj Close'] = c['Stocks'] * c['Close'] / latest_stocks

In [12]:
columns = ['Code', 'Name', 'Min', 'Max', 'Mean', 'Std', 'Current', 'M/C' 'Cdf']
wdf = pd.DataFrame(data)
wdf['C/M'] = 1 / wdf[7]
wdf['Max/Current'] = wdf[3]/wdf[6]
wdf.sort_values([8], ascending=[True]).to_csv('wuryang-%s.csv' % today)
wdf.sort_values([8], ascending=[True]).head(60)

,0,1,2,3,4,5,6,7,8,C/M,Max/Current
358,043200,파루,1160.00,4759.95,2550.29,475.84,1320.00,1.93,0.00,0.52,3.61
75,016250,SGC이테크건설,49350.00,279755.13,182952.80,57119.15,51900.00,3.53,0.01,0.28,5.39
187,046070,코다코,974.00,3840.00,2602.90,791.69,1220.00,2.13,0.04,0.47,3.15
455,006620,동구바이오제약,10750.00,43850.00,22289.62,6729.73,10750.00,2.07,0.04,0.48,4.08
213,099440,스맥,1082.51,3853.91,2668.23,573.57,1730.00,1.54,0.05,0.65,2.23
330,037950,엘컴텍,1225.00,3866.74,2053.98,419.57,1375.00,1.49,0.05,0.67,2.81
109,038060,루멘스,1001.93,5307.24,3031.68,912.45,1730.00,1.75,0.08,0.57,3.07
263,086900,메디톡스,104900.00,807677.76,409307.35,156333.13,191300.00,2.14,0.08,0.47,4.22
95,026040,제이에스티나,1390.00,16000.00,6483.07,3253.89,2075.00,3.12,0.09,0.32,7.71
9,102940,코오롱생명과학,11200.00,127177.66,62441.26,31939.80,19700.00,3.17,0.09,0.32,6.46
26,016100,리더스코스메틱,2128.07,33536.23,12974.29,7506.31,3430.00,3.78,0.10,0.26,9.78
344,234920,자이글,1650.00,13050.00,6844.92,2378.05,3830.00,1.79,0.10,0.56,3.41
452,260930,씨티케이코스메틱스,8850.00,46000.00,21035.55,8716.59,10100.00,2.08,0.10,0.48,4.55
384,255440,야스,7510.00,31141.71,19424.12,5035.48,13150.00,1.48,0.11,0.68,2.37
235,039310,세중,1100.00,5250.00,3434.78,714.78,2545.00,1.35,0.11,0.74,2.06
120,053980,오상자이엘,5350.00,18100.00,9146.97,2068.47,6620.00,1.38,0.11,0.72,2.73
194,040420,정상제이엘에스,5440.00,8450.00,7155.89,604.91,6440.00,1.11,0.12,0.90,1.31
76,035810,이지홀딩스,2321.65,9869.61,6052.56,1183.90,4665.00,1.30,0.12,0.77,2.12
202,009300,삼아제약,9860.00,31750.00,18257.81,2983.87,14800.00,1.23,0.12,0.81,2.15
462,227610,아우딘퓨쳐스,1165.00,13850.00,5417.87,2928.56,2065.00,2.62,0.13,0.38,6.71
305,014200,광림,1425.00,8018.59,3312.78,1472.90,1650.00,2.01,0.13,0.50,4.86
400,225190,삼양옵틱스,7497.99,19717.22,13494.95,3112.75,10000.00,1.35,0.13,0.74,1.97
376,067080,대화제약,5815.03,46990.13,21074.96,8295.94,11800.00,1.79,0.13,0.56,3.98
288,039980,리노스,731.20,4696.59,2122.18,856.70,1175.00,1.81,0.13,0.55,4.00
316,090470,제이스텍,5230.00,28450.00,12881.92,5241.35,7140.00,1.80,0.14,0.55,3.98
293,076610,해성옵틱스,609.72,2852.64,1612.87,467.39,1115.00,1.45,0.14,0.69,2.56
318,228850,레이언스,7210.00,23850.00,16023.61,3462.51,12350.00,1.30,0.14,0.77,1.93
476,066360,체리부로,1140.00,4575.00,2718.84,527.53,2165.00,1.26,0.15,0.80,2.11
157,049520,유아이엘,3485.00,8200.00,5340.41,1086.35,4210.00,1.27,0.15,0.79,1.95
378,217480,에스디생명공학,2360.00,22098.79,9129.74,4240.10,4750.00,1.92,0.15,0.52,4.65
154,093190,빅솔론,3504.46,8058.67,5980.78,989.87,4995.00,1.20,0.16,0.84,1.61
129,052330,코텍,6900.00,18300.00,12995.86,2492.92,10550.00,1.23,0.16,0.81,1.73
311,222040,코스맥스엔비티,2860.00,40650.00,17748.62,9648.97,8310.00,2.14,0.16,0.47,4.89
377,049960,쎌바이오텍,10050.00,66100.00,32305.55,13932.28,18700.00,1.73,0.16,0.58,3.53
61,014620,성광벤드,4095.00,14150.00,9776.05,1824.43,8020.00,1.22,0.17,0.82,1.76
323,064240,홈캐스트,1985.00,28623.70,8204.75,5334.55,3170.00,2.59,0.17,0.39,9.03
124,065510,휴비츠,5400.00,18036.79,10962.46,2891.38,8270.00,1.33,0.18,0.75,2.18
89,018120,진로발효,21100.00,41988.64,34200.25,3232.93,31200.00,1.10,0.18,0.91,1.35
231,011560,세보엠이씨,3350.00,17300.00,8932.48,2758.10,6400.00,1.40,0.18,0.72,2.70
386,067390,아스트,2740.00,13861.27,8467.86,2345.74,6360.00,1.33,0.18,0.75,2.18
106,004650,창해에탄올,8880.00,22095.93,15548.03,2679.77,13150.00,1.18,0.19,0.85,1.68
313,119610,인터로조,16710.35,45173.25,29362.81,6971.39,23150.00,1.27,0.19,0.79,1.95
281,053350,이니텍,2770.00,10700.00,6290.18,1405.67,5040.00,1.25,0.19,0.80,2.12
168,123330,제닉,2010.00,24184.29,10295.65,5436.01,5500.00,1.87,0.19,0.53,4.40
199,007820,에스엠코어,3856.55,18318.91,10348.05,3594.67,7280.00,1.42,0.20,0.70,2.52
364,08537M,루트로닉3우C,7349.73,101919.16,39208.63,29526.26,14050.00,2.79,0.20,0.36,7.25
467,255220,SG,901.86,5422.32,2647.75,885.25,1905.00,1.39,0.20,0.72,2.85
492,021045,대호피앤씨우,1000.00,3440.00,1657.35,408.70,1330.00,1.25,0.21,0.80,2.59
80,067280,멀티캠퍼스,22100.00,55700.00,37616.84,6395.65,32550.00,1.16,0.21,0.87,1.71
197,088910,동우팜투테이블,2010.00,5010.00,3770.44,412.49,3445.00,1.09,0.22,0.91,1.45
74,023160,태광,5670.00,15200.00,9856.63,2081.11,8220.00,1.20,0.22,0.83,1.85
21,051500,CJ프레시웨이,11700.00,59000.00,31508.32,9710.74,23950.00,1.32,0.22,0.76,2.46
345,009780,엠에스씨,3095.00,9350.00,5727.97,1091.72,4880.00,1.17,0.22,0.85,1.92
15,034830,한국토지신탁,1460.00,4020.00,2649.04,593.09,2190.00,1.21,0.22,0.83,1.84
70,115160,휴맥스,1853.92,12400.64,6704.49,2785.22,4575.00,1.47,0.22,0.68,2.71
412,140670,알에스오토메이션,3840.00,29150.00,11927.47,4568.89,8470.00,1.41,0.22,0.71,3.44
483,021040,대호피앤씨,507.00,2450.00,1020.57,266.69,820.00,1.24,0.23,0.80,2.99
504,148150,세경하이테크,14081.74,39550.00,24940.76,5374.88,20950.00,1.19,0.23,0.84,1.89
41,108230,톱텍,6954.82,34158.70,17662.10,7056.99,12500.00,1.41,0.23,0.71,2.73
375,041830,인바디,13500.00,50600.00,27211.95,8882.04,20800.00,1.31,0.24,0.76,2.43

In [13]:
df[df['Code'] == '003380'].iloc[-1]['Close']

9340.0

In [14]:
df[df['Code'] == '054800'].iloc[-1]['Close']

13050.0

In [15]:
df[df['Code'] == '054950'].iloc[-1]

Date            2021-03-29 00:00:00
Code                         054950
Name                          제이브이엠
Market                       KOSDAQ
Dept                          우량기업부
Close                       37700.0
ChangeCode                        1
Changes                       100.0
ChagesRatio                     NaN
Open                        37100.0
High                        37800.0
Low                         37050.0
Volume                      74471.0
Amount                 2788435600.0
Marcap               238675231600.0
Stocks                    6330908.0
MarketId                        KSQ
Rank                            864
ChangesRatio                   0.27
Name: 11214866, dtype: object

In [16]:
wdf[wdf[1]=="파루"]

,0,1,2,3,4,5,6,7,8,C/M,Max/Current
358,043200,파루,1160.00,4759.95,2550.29,475.84,1320.00,1.93,0.00,0.52,3.61