In [94]:
# 우량주 분석
import datetime
today=  datetime.datetime.now()

first = '1995-05-02'

y1_ago = today - datetime.timedelta(days=365)
y3_ago  = today  - datetime.timedelta(days=3*365)
y5_ago = today - datetime.timedelta(days=5*365)
y8_ago = today - datetime.timedelta(days=8*365)
y10_ago = today - datetime.timedelta(days=10*365)

today = today.strftime('%Y-%m-%d')

y1_ago = y1_ago.strftime('%Y-%m-%d')
y3_ago = y3_ago.strftime('%Y-%m-%d')
y5_ago = y5_ago.strftime('%Y-%m-%d')
y8_ago = y8_ago.strftime('%Y-%m-%d')
y10_ago = y10_ago.strftime('%Y-%m-%d')
y1_ago

'2020-03-04'

In [2]:
# 기본 모듈 로드
import pandas as pd
from marcap import marcap_data
import matplotlib.pyplot as plt

In [3]:
# 그래프 설정
import matplotlib.pyplot as plt
import matplotlib.dates as mdates

years = mdates.YearLocator()   # every year
months = mdates.MonthLocator()  # every month
years_fmt = mdates.DateFormatter('%Y')

plt.rcParams["figure.figsize"] = (16,4)
plt.rcParams['lines.linewidth'] = 0.5
plt.rcParams["axes.grid"] = True
plt.rcParams["axes.formatter.useoffset"] = False
plt.rcParams["xtick.minor.visible"] = True 

pd.options.display.float_format = '{:.2f}'.format

In [78]:
df = marcap_data(first, today)

c:\users\j\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py:3338: DtypeWarning: Columns (0) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):
c:\users\j\appdata\local\programs\python\python39\lib\site-packages\IPython\core\interactiveshell.py:3338: DtypeWarning: Columns (3) have mixed types.Specify dtype option on import or set low_memory=False.
  if (await self.run_code(code, result,  async_=asy)):

In [80]:
df['Dept'].unique()
df.reset_index(inplace=True)

In [83]:
df1 = df[df['Date']>y1_ago]
df3 = df[df['Date']>y3_ago]
df5 = df[df['Date']>y5_ago]
df8 = df[df['Date']>y8_ago]
df10 = df[df['Date']>y10_ago]

df1_10 = df[df['Date']>y10_ago]
df1_10 = df1_10[df1_10['Date']<y1_ago]
df1_5 = df[df['Date']>y5_ago]
df1_5 = df1_5[df1_5['Date']<y1_ago]

,Date,Code,Name,Market,Dept,Close,ChangeCode,Changes,ChagesRatio,Open,High,Low,Volume,Amount,Marcap,Stocks,MarketId,Rank,ChangesRatio
8404392,2016-03-07,005930,삼성전자,KOSPI,NaN,1223000.00,1,8000.00,0.66,1220000.00,1231000.00,1215000.00,131376.00,160439055900.00,177419799151000.00,145069337.00,STK,1,NaN
8404393,2016-03-07,015760,한국전력,KOSPI,NaN,56800.00,2,-1600.00,-2.74,58000.00,58200.00,56100.00,2088653.00,118161576000.00,36463559573600.00,641964077.00,STK,2,NaN
8404394,2016-03-07,005380,현대차,KOSPI,NaN,146500.00,2,-1000.00,-0.68,147500.00,147500.00,145500.00,317439.00,46423351500.00,32270504173500.00,220276479.00,STK,3,NaN
8404395,2016-03-07,028260,삼성물산,KOSPI,NaN,152500.00,2,-1500.00,-0.97,154000.00,156500.00,152500.00,345376.00,53025546500.00,28927731557500.00,189690043.00,STK,4,NaN
8404396,2016-03-07,012330,현대모비스,KOSPI,NaN,254000.00,1,2500.00,0.99,252000.00,255500.00,249000.00,144983.00,36620158500.00,24725341202000.00,97343863.00,STK,5,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10589147,2020-03-03,001799,대한제당3우B,KOSPI,NaN,20150.00,2,-550.00,-2.66,20850.00,20850.00,20050.00,1399.00,28272650.00,2612568400.00,129656.00,STK,2469,NaN
10589148,2020-03-03,001529,동양3우B,KOSPI,NaN,26350.00,2,-50.00,-0.19,26350.00,26350.00,25600.00,8131.00,219293000.00,2364174700.00,89722.00,STK,2470,NaN
10589149,2020-03-03,238500,로보쓰리,KONEX,일반기업부,478.00,1,48.00,11.16,486.00,486.00,367.00,2685.00,996142.00,2238075348.00,4682166.00,KNX,2472,NaN
10589150,2020-03-03,267810,앙츠,KONEX,일반기업부,1345.00,1,35.00,2.67,1345.00,1345.00,1345.00,744.00,1000680.00,2080715000.00,1547000.00,KNX,2473,NaN
10589151,2020-03-03,208890,에듀파트너,KONEX,일반기업부,900.00,1,50.00,5.88,900.00,900.00,900.00,5.00,4500.00,1935738000.00,2150820.00,KNX,2474,NaN

In [85]:
d = df1_10

In [86]:
wuryang = d[d['Dept'] == '우량기업부']

In [87]:
codes = wuryang['Code'].unique()

In [88]:
len(codes)

864

In [95]:
data = list()
import scipy.stats
# for code in codes:


for code in codes:
    c = d[d['Code'] == code]
    if c['Date'].iloc[-1] == pd.to_datetime('2020-03-03'):
        latest_stocks = c['Stocks'].iloc[-1]
        c['Adj Close'] = c['Stocks'] * c['Close'] / latest_stocks

        c_min = c['Adj Close'].min()
        c_max = c['Adj Close'].max()
        c_mean = c['Adj Close'].mean()
        c_std = c['Adj Close'].std()

        c_current = c['Adj Close'].iloc[-1]

        c_norm = scipy.stats.norm(c_mean, c_std)

        data.append([code, c['Name'].iloc[-1], c_min, c_max, c_mean, c_std, c_current, c_mean/c_current, c_norm.cdf(c_current)])

<ipython-input-95-f9d031bee500>:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  c['Adj Close'] = c['Stocks'] * c['Close'] / latest_stocks

In [96]:
columns = ['Code', 'Name', 'Min', 'Max', 'Mean', 'Std', 'Current', 'M/C' 'Cdf']
wdf = pd.DataFrame(data)
wdf['C/M'] = 1 / wdf[7]
wdf.sort_values([8], ascending=[True]).head(60)

,0,1,2,3,4,5,6,7,8,C/M
237,054800,아이디스홀딩스,10100.00,18400.00,14640.97,1391.60,10550.00,1.39,0.00,0.72
156,054950,제이브이엠,21850.00,67500.00,48822.72,10108.39,22200.00,2.20,0.00,0.45
417,003380,하림지주,7060.00,14395.36,11205.11,1633.91,7170.00,1.56,0.01,0.64
46,106190,하이텍팜,9750.00,20300.00,13949.22,1632.79,9920.00,1.41,0.01,0.71
248,094850,참좋은여행,5190.00,16700.00,9625.48,1884.65,5210.00,1.85,0.01,0.54
35,095910,에스에너지,3120.00,10478.13,6937.17,1582.60,3275.00,2.12,0.01,0.47
263,039310,세중,2170.00,6673.81,3967.07,766.59,2210.00,1.80,0.01,0.56
138,078020,이베스트투자증권,4042.20,12805.15,7188.58,1025.77,4890.00,1.47,0.01,0.68
396,234920,자이글,3870.00,13050.00,7848.50,1744.78,3965.00,1.98,0.01,0.51
29,086960,한컴MDS,9210.00,28857.45,18700.67,3990.82,9860.00,1.90,0.01,0.53
110,028150,GS홈쇼핑,124000.00,307800.00,202304.65,34936.76,125200.00,1.62,0.01,0.62
444,225190,삼양옵틱스,10300.00,19722.50,15090.77,2093.43,10500.00,1.44,0.01,0.70
234,011370,서한,963.00,3280.00,1997.38,458.28,1000.00,2.00,0.01,0.50
355,036640,HRS,1940.00,5530.00,3659.30,650.85,2245.00,1.63,0.01,0.61
439,241710,코스메카코리아,9960.00,41400.00,26721.74,7729.42,9960.00,2.68,0.02,0.37
467,087260,모바일어플라이언스,2425.00,14250.00,7270.27,2241.46,2425.00,3.00,0.02,0.33
209,036190,금화피에스시,23700.00,54100.00,37333.93,6441.06,23700.00,1.58,0.02,0.63
244,099440,스맥,1800.00,6188.51,3272.09,624.24,1960.00,1.67,0.02,0.60
238,104200,NHN벅스,4585.00,16513.09,9576.14,2385.21,4590.00,2.09,0.02,0.48
33,041440,에버다임,3765.00,13750.00,8281.68,2161.90,3780.00,2.19,0.02,0.46
344,004780,대륙제관,3680.00,9600.00,6163.02,1172.34,3725.00,1.65,0.02,0.60
7,080520,오디텍,4095.00,13111.78,8126.08,1899.81,4280.00,1.90,0.02,0.53
23,003100,선광,14150.00,28000.00,19029.11,2240.32,14500.00,1.31,0.02,0.76
252,040610,SG&G,1525.00,6330.00,3304.10,874.54,1545.00,2.14,0.02,0.47
431,255440,야스,14900.00,31141.71,22155.91,3422.01,15350.00,1.44,0.02,0.69
222,093190,빅솔론,3504.46,8694.88,6573.13,830.84,4935.00,1.33,0.02,0.75
159,013030,하이록코리아,14150.00,38900.00,24896.25,5431.88,14250.00,1.75,0.03,0.57
44,037350,성도이엔지,3245.00,9570.00,5628.73,1199.31,3305.00,1.70,0.03,0.59
390,228340,동양파일,2450.00,11400.00,6136.34,1930.13,2485.00,2.47,0.03,0.40
151,044490,태웅,6950.00,30100.00,17246.83,5460.18,7000.00,2.46,0.03,0.41
371,228850,레이언스,10600.00,23850.00,17274.08,2789.50,12100.00,1.43,0.03,0.70
217,036560,영풍정밀,6830.00,12050.00,9125.96,899.07,7460.00,1.22,0.03,0.82
80,126640,화신정공,985.00,2050.00,1462.28,203.61,1085.00,1.35,0.03,0.74
253,122350,삼기오토모티브,1923.03,4741.57,3248.24,618.78,2120.00,1.53,0.03,0.65
140,054050,농우바이오,9550.00,26761.38,17358.84,4129.02,9840.00,1.76,0.03,0.57
219,026040,제이에스티나,2500.00,21550.00,9632.15,3964.44,2500.00,3.85,0.04,0.26
446,140070,서플러스글로벌,1995.00,4840.00,3314.89,715.99,2045.00,1.62,0.04,0.62
137,030520,한글과컴퓨터,8981.55,25594.10,16786.06,3744.06,10150.00,1.65,0.04,0.60
175,115160,휴맥스,4330.00,19650.00,11034.41,3813.12,4335.00,2.55,0.04,0.39
293,049080,기가레인,1115.00,4521.26,2391.08,685.55,1190.00,2.01,0.04,0.50
265,076080,웰크론한텍,1635.00,4603.76,2709.14,612.00,1655.00,1.64,0.04,0.61
486,110790,크리스에프앤씨,15000.00,27200.00,21470.71,2718.47,16800.00,1.28,0.04,0.78
307,042110,에스씨디,890.00,2640.00,1747.76,350.98,1145.00,1.53,0.04,0.66
366,222040,코스맥스엔비티,5490.00,40650.00,20896.64,8843.41,5890.00,3.55,0.04,0.28
178,095500,미래나노텍,2506.69,10392.43,5076.77,1393.59,2745.00,1.85,0.05,0.54
146,114120,크루셜텍,404.00,7308.61,3350.58,1764.83,404.00,8.29,0.05,0.12
476,212560,네오오토,3710.00,10800.00,5968.12,1199.34,3970.00,1.50,0.05,0.67
273,063080,게임빌,21300.00,182364.08,68786.54,27945.92,22500.00,3.06,0.05,0.33
60,088910,동우팜투테이블,2659.30,5221.25,3798.75,407.07,3125.00,1.22,0.05,0.82
496,007680,대원,9900.00,20847.03,12152.01,1365.99,9900.00,1.23,0.05,0.81
278,053980,오상자이엘,5350.00,23734.17,10453.73,3123.84,5350.00,1.95,0.05,0.51
17,036000,예림당,2790.00,15300.00,6413.77,2185.52,2850.00,2.25,0.05,0.44
315,081580,성우전자,2370.00,8990.00,4440.59,1150.86,2585.00,1.72,0.05,0.58
501,255220,SG,960.43,5483.30,3015.90,907.19,1565.00,1.93,0.05,0.52
67,038950,파인디지털,2800.00,9031.42,5713.91,1380.20,3510.00,1.63,0.06,0.61
207,005160,동국산업,2150.00,5899.22,3557.31,758.18,2355.00,1.51,0.06,0.66
13,123330,제닉,4000.00,41490.00,16052.15,7562.99,4120.00,3.90,0.06,0.26
489,260930,씨티케이코스메틱스,11000.00,46000.00,24530.07,8601.27,11000.00,2.23,0.06,0.45
345,039980,리노스,1165.00,4926.53,2494.99,725.56,1355.00,1.84,0.06,0.54
15,101390,아이엠,767.13,3271.14,1669.14,449.84,965.00,1.73,0.06,0.58

In [97]:
df[df['Code'] == '003380'].iloc[-1]['Close']

8730.0

In [98]:
df[df['Code'] == '054800'].iloc[-1]['Close']

12650.0

In [99]:
df[df['Code'] == '054950'].iloc[-1]

Date            2021-03-04 00:00:00
Code                         054950
Name                          제이브이엠
Market                       KOSDAQ
Dept                          우량기업부
Close                       33250.0
ChangeCode                        2
Changes                      -100.0
ChagesRatio                     NaN
Open                        33250.0
High                        33650.0
Low                         32700.0
Volume                      33500.0
Amount                 1108748750.0
Marcap               210502691000.0
Stocks                    6330908.0
MarketId                        KSQ
Rank                            931
ChangesRatio                   -0.3
Name: 11173550, dtype: object